// GENERATED by tools/gen-models.mjs from the Kotlin models. Do not edit; run `npm run generate`.
/* eslint-disable */
import { Rec, type RawRecord } from "./fields.js";
import {
  coordinates, eventStatus, externalIds, leagueRefs, numeric, roundStage, socials,
  type ApiRecord, type EventStatus, type LeagueRef, type PlayerExternalIds, type RoundStage, type Socials,
} from "./model-support.js";

/**
 * A sport (`all_sports.php`, `all/sports`).
 */
export interface Sport extends ApiRecord {
  readonly kind: "Sport";
  /** `idSport` */
  readonly id: number | null;
  /** `strSport`, e.g. `Ice Hockey`. Use this name for sport filters. */
  readonly name: string | null;
  /** `strFormat`: `TeamvsTeam` or `EventSport`. */
  readonly format: string | null;
  /** `strSportDescription` */
  readonly description: string | null;
  /** `strSportThumb` */
  readonly thumb: string | null;
  /** `strSportThumbBW` */
  readonly thumbBlackAndWhite: string | null;
  /** `strSportIconGreen` */
  readonly icon: string | null;
}

/**
 * A country (`all_countries.php`, `all/countries`). v1 returns only [name] and [flag32].
 */
export interface Country extends ApiRecord {
  readonly kind: "Country";
  /** `name_en`. Use this name for country filters. */
  readonly name: string | null;
  /** `name_fr` (v2) */
  readonly nameFr: string | null;
  /** `code` (v2), a two-letter code */
  readonly code: string | null;
  /** `flag_url_16` (v2) */
  readonly flag16: string | null;
  /** `flag_url_32` */
  readonly flag32: string | null;
  /** `flag_url_64` (v2) */
  readonly flag64: string | null;
  /** `idAPIfootball` (v2) */
  readonly apiFootballId: number | null;
}

/**
 * A league or cup. Lists (`all_leagues.php`, v2 `search/league`) fill only a few fields;
 * look it up by id for the rest.
 *
 */
export interface League extends ApiRecord {
  readonly kind: "League";
  /** `idLeague` */
  readonly id: number | null;
  /** `strLeague` */
  readonly name: string | null;
  /** `strLeagueAlternate`, split on commas */
  readonly alternateNames: readonly string[];
  /** `strSport` */
  readonly sport: string | null;
  /** `strCountry` */
  readonly country: string | null;
  /** `strGender` */
  readonly gender: string | null;
  /** `strCurrentSeason`, e.g. `2026-2027` or `2026`. Pass it to season endpoints. */
  readonly currentSeason: string | null;
  /** `intDivision`: 1 for a top flight; cups often use 0 or 99 */
  readonly division: number | null;
  /** `idCup`: true for a cup competition */
  readonly isCup: boolean | null;
  /** `intFormedYear` */
  readonly formedYear: number | null;
  /** `dateFirstEvent` (YYYY-MM-DD) */
  readonly firstEventDate: string | null;
  /** `strComplete`: whether TheSportsDB considers its data complete */
  readonly isComplete: boolean | null;
  /** `strNaming`: the event-name template, e.g. `{strHomeTeam} vs {strAwayTeam}` */
  readonly eventNaming: string | null;
  /** `strTvRights`: free text */
  readonly tvRights: string | null;
  /** `strBadge` */
  readonly badge: string | null;
  /** `strLogo` */
  readonly logo: string | null;
  /** `strBanner` */
  readonly banner: string | null;
  /** `strPoster` */
  readonly poster: string | null;
  /** `strTrophy` */
  readonly trophy: string | null;
  /** `strFanart1`..`strFanart4` */
  readonly fanart: readonly string[];
  /** `strDescriptionEN`, `strDescriptionDE`, ... keyed by language code (`EN`, `DE`) */
  readonly descriptions: Readonly<Record<string, string>>;
  readonly socials: Socials;
  /** `strLocked` */
  readonly isLocked: boolean | null;
  /** `idAPIfootball` */
  readonly apiFootballId: number | null;
  /** `idAPIfootballv3` */
  readonly apiFootballV3Id: number | null;
  /** The English description. */
  readonly description: string | null;
}

/**
 * A season of a league (`search_all_seasons.php`, `list/seasons`).
 */
export interface Season extends ApiRecord {
  readonly kind: "Season";
  /** `strSeason`, e.g. `2026-2027` */
  readonly name: string;
  /** `strBadge` (v2, or v1 with `badge=1`) */
  readonly badge: string | null;
  /** `strPoster` (v2, or v1 with `poster=1`) */
  readonly poster: string | null;
  /** `strDescriptionEN` (v2, or v1 with `description=1`) */
  readonly description: string | null;
}

/**
 * One season poster or badge uploaded for a league (v2 `list/seasonposters`). A season can have
 * several; each is a separate piece of artwork with its own id.
 *
 */
export interface SeasonPoster extends ApiRecord {
  readonly kind: "SeasonPoster";
  /** `idArt`: this artwork's id */
  readonly id: number | null;
  /** `idLeague` */
  readonly leagueId: number | null;
  /** `strSeason`, e.g. `2025-2026` */
  readonly season: string | null;
  /** `strPoster` */
  readonly poster: string | null;
  /** `strBadge` */
  readonly badge: string | null;
  /** `strDescriptionEN` */
  readonly description: string | null;
  /** `strUsername`: who uploaded it */
  readonly uploadedBy: string | null;
}

/**
 * A team. Search and list endpoints fill only some fields (v2 `list/teams` has no
 * alternate names, for example); a lookup by id fills them all.
 *
 */
export interface Team extends ApiRecord {
  readonly kind: "Team";
  /** `idTeam` */
  readonly id: number | null;
  /** `strTeam` */
  readonly name: string | null;
  /** `strTeamShort`, e.g. `ARS` */
  readonly shortName: string | null;
  /** `strTeamAlternate`, split on commas */
  readonly alternateNames: readonly string[];
  /** `strKeywords`, split on commas (nicknames) */
  readonly keywords: readonly string[];
  /** `strSport` */
  readonly sport: string | null;
  /** `strGender` */
  readonly gender: string | null;
  /** `strCountry` */
  readonly country: string | null;
  /** `strLocation` */
  readonly location: string | null;
  /** `intFormedYear` */
  readonly formedYear: number | null;
  /** `idLeague`/`strLeague`: the main league */
  readonly leagueId: number | null;
  /** `strLeague` */
  readonly league: string | null;
  /** Every league and cup the team is entered in: `idLeague`..`idLeague7` with their names */
  readonly leagues: readonly LeagueRef[];
  /** `strDivision` */
  readonly division: string | null;
  /** `idVenue` */
  readonly venueId: number | null;
  /** `strStadium` */
  readonly stadium: string | null;
  /** `strColour1`..`strColour3`, hex like `#EF0107` */
  readonly colours: readonly string[];
  /** `strBadge` */
  readonly badge: string | null;
  /** `strLogo` */
  readonly logo: string | null;
  /** `strBanner` */
  readonly banner: string | null;
  /** `strEquipment`: the current kit image */
  readonly equipment: string | null;
  /** `strFanart1`..`strFanart4` */
  readonly fanart: readonly string[];
  /** `strDescriptionEN`, `strDescriptionDE`, ... keyed by language code */
  readonly descriptions: Readonly<Record<string, string>>;
  readonly socials: Socials;
  /** `intLoved` */
  readonly loved: number | null;
  /** `strLocked` */
  readonly isLocked: boolean | null;
  /** `idAPIfootball` */
  readonly apiFootballId: number | null;
  /** `idESPN` */
  readonly espnId: string | null;
  /** The English description. */
  readonly description: string | null;
}

/**
 * A game, match, race or other event. Also used for video highlights.
 *
 * Schedules and lists fill fewer fields than a lookup by id: v1 `eventsseason.php` and v2
 * `schedule/...` leave out descriptions, officials, spectators and the like.
 *
 * **Times:** [timestamp], [date] and [time] are UTC. [localDate] and [localTime] are the
 * venue's local time and are often missing for future events.
 *
 */
export interface Event extends ApiRecord {
  readonly kind: "Event";
  /** `idEvent` */
  readonly id: number | null;
  /** `strEvent`, e.g. `Arsenal vs Chelsea` */
  readonly name: string | null;
  /** `strEventAlternate`, e.g. `Chelsea @ Arsenal` */
  readonly alternateName: string | null;
  /** `strFilename`: `{league} {date} {home} vs {away}`, searchable with `searchfilename.php` */
  readonly filename: string | null;
  /** `strSport` */
  readonly sport: string | null;
  /** `idLeague` */
  readonly leagueId: number | null;
  /** `strLeague` */
  readonly league: string | null;
  /** `strLeagueBadge` */
  readonly leagueBadge: string | null;
  /** `strSeason` */
  readonly season: string | null;
  /** `intRound`: matchday or round number, or a stage code (125 quarter-final … 500 pre-season); see [stage] */
  readonly round: number | null;
  /** `strGroup`: a cup group or conference */
  readonly group: string | null;
  /** `idHomeTeam` */
  readonly homeTeamId: number | null;
  /** `strHomeTeam` */
  readonly homeTeam: string | null;
  /** `strHomeTeamBadge` */
  readonly homeTeamBadge: string | null;
  /** `idAwayTeam` */
  readonly awayTeamId: number | null;
  /** `strAwayTeam` */
  readonly awayTeam: string | null;
  /** `strAwayTeamBadge` */
  readonly awayTeamBadge: string | null;
  /** `intHomeScore`: null until the event has a score */
  readonly homeScore: number | null;
  /** `intAwayScore` */
  readonly awayScore: number | null;
  /** `intHomeScoreExtra`: extra time or shoot-out */
  readonly homeScoreExtra: number | null;
  /** `intAwayScoreExtra` */
  readonly awayScoreExtra: number | null;
  /** `strTimestamp`: the start time (UTC) (UTC) */
  readonly timestamp: Date | null;
  /** `dateEvent` (UTC) (YYYY-MM-DD) */
  readonly date: string | null;
  /** `strTime` (UTC) (HH:MM:SS) */
  readonly time: string | null;
  /** `dateEventLocal`: the venue's local date (YYYY-MM-DD) */
  readonly localDate: string | null;
  /** `strTimeLocal`: the venue's local time (HH:MM:SS) */
  readonly localTime: string | null;
  /** `strStatus`: the raw code (`NS`, `2H`, `FT`, `Q3`, `PST`...); see [status] */
  readonly statusCode: string | null;
  /** `strPostponed` */
  readonly isPostponed: boolean | null;
  /** `idVenue` */
  readonly venueId: number | null;
  /** `strVenue` */
  readonly venue: string | null;
  /** `strCity` */
  readonly city: string | null;
  /** `strCountry` */
  readonly country: string | null;
  /** `intSpectators` */
  readonly spectators: number | null;
  /** `strOfficial`: the referee */
  readonly official: string | null;
  /** `strResult`: free-text result, sometimes with HTML `<br>` */
  readonly resultText: string | null;
  /** `strDescriptionEN` */
  readonly description: string | null;
  /** `strThumb` */
  readonly thumb: string | null;
  /** `strPoster` */
  readonly poster: string | null;
  /** `strBanner` */
  readonly banner: string | null;
  /** `strSquare` */
  readonly square: string | null;
  /** `strFanart` */
  readonly fanart: string | null;
  /** `strMap` */
  readonly map: string | null;
  /** `strVideo`: a highlights video, usually YouTube */
  readonly video: string | null;
  /** `strTweet1` */
  readonly tweet: string | null;
  /** `strWeather` */
  readonly weather: string | null;
  /** `intScore`: the users' rating of the event */
  readonly rating: number | null;
  /** `intScoreVotes` */
  readonly ratingVotes: number | null;
  /** `strLocked` */
  readonly isLocked: boolean | null;
  /** `idAPIfootball` */
  readonly apiFootballId: number | null;
  /** The status code read as a broad status. */
  readonly status: EventStatus;
  /** The stage when `round` is a stage code (e.g. 200 = final), or null for an ordinary round. */
  readonly stage: RoundStage | null;
}

/**
 * One row of a league table (`lookuptable.php`). v1 only; there is no v2 equivalent.
 */
export interface Standing extends ApiRecord {
  readonly kind: "Standing";
  /** `idStanding` */
  readonly id: number | null;
  /** `intRank` */
  readonly rank: number | null;
  /** `idTeam` */
  readonly teamId: number | null;
  /** `strTeam` */
  readonly team: string | null;
  /** `strBadge` */
  readonly badge: string | null;
  /** `idLeague` */
  readonly leagueId: number | null;
  /** `strLeague` */
  readonly league: string | null;
  /** `strSeason` */
  readonly season: string | null;
  /** `strGroup` */
  readonly group: string | null;
  /** `strForm`: recent results, newest last, e.g. `WWDLW` */
  readonly form: string | null;
  /** `strDescription`: what this position leads to, e.g. `Promotion - Champions League` */
  readonly description: string | null;
  /** `intPlayed` */
  readonly played: number | null;
  /** `intWin` */
  readonly won: number | null;
  /** `intDraw` */
  readonly drawn: number | null;
  /** `intLoss` */
  readonly lost: number | null;
  /** `intGoalsFor` */
  readonly goalsFor: number | null;
  /** `intGoalsAgainst` */
  readonly goalsAgainst: number | null;
  /** `intGoalDifference` */
  readonly goalDifference: number | null;
  /** `intPoints` */
  readonly points: number | null;
  /** `dateUpdated` (zone not stated) (YYYY-MM-DDTHH:MM:SS, zone not stated) */
  readonly updated: string | null;
}

/**
 * One player in an event's lineup (`lookuplineup.php`, `lookup/event_lineup`).
 */
export interface LineupEntry extends ApiRecord {
  readonly kind: "LineupEntry";
  /** `idLineup` */
  readonly id: number | null;
  /** `idEvent` */
  readonly eventId: number | null;
  /** `strEvent` (v2) */
  readonly event: string | null;
  /** `idPlayer` */
  readonly playerId: number | null;
  /** `strPlayer` */
  readonly player: string | null;
  /** `idTeam` */
  readonly teamId: number | null;
  /** `strTeam` */
  readonly team: string | null;
  /** `strHome`: true for the home side */
  readonly isHome: boolean | null;
  /** `strSubstitute`: true for the bench */
  readonly isSubstitute: boolean | null;
  /** `strPosition` */
  readonly position: string | null;
  /** `strPositionShort` (v2), e.g. `G`, `D` */
  readonly positionShort: string | null;
  /** `strFormation` (v2), e.g. `4-3-3` */
  readonly formation: string | null;
  /** `intSquadNumber` */
  readonly squadNumber: number | null;
  /** `strCountry` (v2) */
  readonly country: string | null;
  /** `strSeason` (v2) */
  readonly season: string | null;
  /** `strThumb` (v1) */
  readonly thumb: string | null;
  /** `strCutout` */
  readonly cutout: string | null;
  /** `strRender` (v1) */
  readonly render: string | null;
  /** `idAPIfootball` (v2) */
  readonly apiFootballId: number | null;
}

/**
 * A goal, card or substitution during an event (`lookuptimeline.php`, `lookup/event_timeline`).
 */
export interface TimelineEntry extends ApiRecord {
  readonly kind: "TimelineEntry";
  /** `idTimeline` */
  readonly id: number | null;
  /** `idEvent` */
  readonly eventId: number | null;
  /** `strEvent` */
  readonly event: string | null;
  /** `dateEvent` (YYYY-MM-DD) */
  readonly date: string | null;
  /** `strSeason` */
  readonly season: string | null;
  /** `intTime`: the minute */
  readonly minute: number | null;
  /** `strPeriod` */
  readonly period: string | null;
  /** `strTimeline`: the kind of entry, e.g. `Goal`, `Card`, `subst` */
  readonly type: string | null;
  /** `strTimelineDetail`, e.g. `Yellow Card`, `Normal Goal`, or the player coming on */
  readonly detail: string | null;
  /** `strComment` */
  readonly comment: string | null;
  /** `idPlayer` */
  readonly playerId: number | null;
  /** `strPlayer` */
  readonly player: string | null;
  /** `strCutout` */
  readonly cutout: string | null;
  /** `idAssist` */
  readonly assistId: number | null;
  /** `strAssist` */
  readonly assist: string | null;
  /** `idTeam` */
  readonly teamId: number | null;
  /** `strTeam` */
  readonly team: string | null;
  /** `strHome` */
  readonly isHome: boolean | null;
  /** `idAPIfootball` */
  readonly apiFootballId: number | null;
}

/**
 * One team statistic for an event, home vs away (`lookupeventstats.php`, `lookup/event_stats`).
 */
export interface EventStat extends ApiRecord {
  readonly kind: "EventStat";
  /** `idStatistic` */
  readonly id: number | null;
  /** `idEvent` */
  readonly eventId: number | null;
  /** `strEvent` */
  readonly event: string | null;
  /** `strStat`, e.g. `Shots on Goal`, `Ball Possession` */
  readonly name: string | null;
  /** `intHome` */
  readonly home: number | null;
  /** `intAway` */
  readonly away: number | null;
  /** `idApiFootball` (note the different capitalisation in the API) */
  readonly apiFootballId: number | null;
}

/**
 * One broadcast of an event on one channel (v1 `lookuptv.php`/`eventstv.php`, v2 `lookup/event_tv`/`filter/tv`).
 */
export interface TvListing extends ApiRecord {
  readonly kind: "TvListing";
  /** `id` */
  readonly id: number | null;
  /** `idEvent` */
  readonly eventId: number | null;
  /** `strEvent` */
  readonly event: string | null;
  /** `strSport` */
  readonly sport: string | null;
  /** `strSeason` */
  readonly season: string | null;
  /** `idChannel` */
  readonly channelId: number | null;
  /** `strChannel`, e.g. `TSN 1` */
  readonly channel: string | null;
  /** `strLogo`: the channel logo */
  readonly channelLogo: string | null;
  /** `strCountry`: the channel's country */
  readonly country: string | null;
  /** `strEventCountry`: where the event takes place */
  readonly eventCountry: string | null;
  /** `strTimeStamp` (capital S, space-separated in the API): broadcast start, UTC (UTC) */
  readonly timestamp: Date | null;
  /** `dateEvent` (YYYY-MM-DD) */
  readonly date: string | null;
  /** `strTime` (HH:MM:SS) */
  readonly time: string | null;
  /** `intDivision` */
  readonly division: number | null;
  /** `strEventThumb` */
  readonly eventThumb: string | null;
  /** `strEventPoster` */
  readonly eventPoster: string | null;
  /** `strEventBanner` */
  readonly eventBanner: string | null;
  /** `strEventSquare` */
  readonly eventSquare: string | null;
}

/**
 * A game in progress (`livescore.php`, `livescore/...`).
 */
export interface LiveScore extends ApiRecord {
  readonly kind: "LiveScore";
  /** `idLiveScore` */
  readonly id: number | null;
  /** `idEvent` */
  readonly eventId: number | null;
  /** `strSport` */
  readonly sport: string | null;
  /** `idLeague` */
  readonly leagueId: number | null;
  /** `strLeague` */
  readonly league: string | null;
  /** `intDivision` */
  readonly division: number | null;
  /** `idHomeTeam` */
  readonly homeTeamId: number | null;
  /** `strHomeTeam` */
  readonly homeTeam: string | null;
  /** `strHomeTeamBadge` */
  readonly homeTeamBadge: string | null;
  /** `idAwayTeam` */
  readonly awayTeamId: number | null;
  /** `strAwayTeam` */
  readonly awayTeam: string | null;
  /** `strAwayTeamBadge` */
  readonly awayTeamBadge: string | null;
  /** `intHomeScore` */
  readonly homeScore: number | null;
  /** `intAwayScore` */
  readonly awayScore: number | null;
  /** `strStatus`: the raw code; see [status] */
  readonly statusCode: string | null;
  /** `strProgress`: the minute (soccer) or `Final` */
  readonly progress: string | null;
  /** `strEventTime`: kick-off, `HH:mm` (HH:MM:SS) */
  readonly eventTime: string | null;
  /** `dateEvent` (YYYY-MM-DD) */
  readonly date: string | null;
  /** `strTimestamp`: kick-off, UTC (UTC) */
  readonly timestamp: Date | null;
  /** `updated`: when this score was last refreshed (zone not stated) (YYYY-MM-DDTHH:MM:SS, zone not stated) */
  readonly updated: string | null;
  /** The status code read as a broad status. */
  readonly status: EventStatus;
}

/**
 * A player, manager or other person. Search and list endpoints fill only some fields;
 * look the player up by id for the rest.
 *
 */
export interface Player extends ApiRecord {
  readonly kind: "Player";
  /** `idPlayer` */
  readonly id: number | null;
  /** `strPlayer` */
  readonly name: string | null;
  /** `strPlayerAlternate` */
  readonly alternateName: string | null;
  /** `strLastName` */
  readonly lastName: string | null;
  /** `idTeam` */
  readonly teamId: number | null;
  /** `strTeam` */
  readonly team: string | null;
  /** `idTeam2` */
  readonly secondTeamId: number | null;
  /** `strTeam2`, often the national team */
  readonly secondTeam: string | null;
  /** `idTeamNational` */
  readonly nationalTeamId: number | null;
  /** `idPlayerManager`: this person's record as a manager */
  readonly managerId: number | null;
  /** `strSport` */
  readonly sport: string | null;
  /** `strNationality` */
  readonly nationality: string | null;
  /** `strPosition` */
  readonly position: string | null;
  /** `strNumber`: the shirt number, as text */
  readonly number: string | null;
  /** `strStatus`, e.g. `Active`, `Retired` */
  readonly status: string | null;
  /** `strGender` */
  readonly gender: string | null;
  /** `dateBorn` (YYYY-MM-DD) */
  readonly born: string | null;
  /** `strBirthLocation` */
  readonly birthLocation: string | null;
  /** `dateDied` (YYYY-MM-DD) */
  readonly died: string | null;
  /** `strDeathLocation` */
  readonly deathLocation: string | null;
  /** `dateSigned` (YYYY-MM-DD) */
  readonly signed: string | null;
  /** `strSigning`: the fee as text, e.g. `£25.20m` */
  readonly signing: string | null;
  /** `strWage`, as text */
  readonly wage: string | null;
  /** `strAgent` */
  readonly agent: string | null;
  /** `strHeight`, as text: `1.82 m (6 ft 0 in)` or `186 cm` */
  readonly height: string | null;
  /** `strWeight`, as text */
  readonly weight: string | null;
  /** `strSide`: `Left`/`Right` (preferred foot or hand) */
  readonly side: string | null;
  /** `strKit`: boot or equipment model */
  readonly kit: string | null;
  /** `strOutfitter` */
  readonly outfitter: string | null;
  /** `strCollege` */
  readonly college: string | null;
  /** `strEthnicity` */
  readonly ethnicity: string | null;
  /** `strThumb` */
  readonly thumb: string | null;
  /** `strCutout`: transparent head-and-shoulders */
  readonly cutout: string | null;
  /** `strRender`: transparent full body */
  readonly render: string | null;
  /** `strCartoon` */
  readonly cartoon: string | null;
  /** `strBanner` */
  readonly banner: string | null;
  /** `strPoster` */
  readonly poster: string | null;
  /** `strFanart1`..`strFanart4` */
  readonly fanart: readonly string[];
  /** `strCreativeCommons`: whether the artwork is Creative Commons. TheSportsDB's terms say artwork that isn't (false or null) must not be used in published apps. */
  readonly creativeCommons: boolean | null;
  /** `strCreativeCommonsAttribution`: the credit line to show */
  readonly creativeCommonsAttribution: string | null;
  /** `strDescriptionEN`, ... keyed by language code */
  readonly descriptions: Readonly<Record<string, string>>;
  readonly socials: Socials;
  /** `intLoved` */
  readonly loved: number | null;
  /** `strLocked` */
  readonly isLocked: boolean | null;
  /** `relevance`: search score (v1 `searchplayers.php` only) */
  readonly relevance: number | null;
  readonly externalIds: PlayerExternalIds;
  /** The English description. */
  readonly description: string | null;
}

/**
 * A trophy a player won (`lookuphonours.php`, `lookup/player_honours`).
 */
export interface Honour extends ApiRecord {
  readonly kind: "Honour";
  /** `id`: this record */
  readonly id: number | null;
  /** `idHonour`: the honour itself, shared by everyone who won it */
  readonly honourId: number | null;
  /** `strHonour`, e.g. `Copa Libertadores` */
  readonly name: string | null;
  /** `strSeason` */
  readonly season: string | null;
  /** `idPlayer` */
  readonly playerId: number | null;
  /** `strPlayer` */
  readonly player: string | null;
  /** `idTeam` */
  readonly teamId: number | null;
  /** `strTeam` */
  readonly team: string | null;
  /** `strTeamBadge` */
  readonly teamBadge: string | null;
  /** `idLeague` */
  readonly leagueId: number | null;
  /** `strSport` */
  readonly sport: string | null;
  /** `strHonourLogo` */
  readonly logo: string | null;
  /** `strHonourTrophy` */
  readonly trophy: string | null;
}

/**
 * A team a player used to play for (`lookupformerteams.php`, `lookup/player_teams`).
 */
export interface FormerTeam extends ApiRecord {
  readonly kind: "FormerTeam";
  /** `id` */
  readonly id: number | null;
  /** `idPlayer` */
  readonly playerId: number | null;
  /** `strPlayer` */
  readonly player: string | null;
  /** `idFormerTeam`: the team's `idTeam` */
  readonly teamId: number | null;
  /** `strFormerTeam` */
  readonly team: string | null;
  /** `strBadge` */
  readonly badge: string | null;
  /** `strJoined`: usually a year, as text */
  readonly joined: string | null;
  /** `strDeparted`: usually a year, as text */
  readonly departed: string | null;
  /** `strMoveType`, e.g. `Permanent`, `Loan` */
  readonly moveType: string | null;
  /** `intAppearances` */
  readonly appearances: number | null;
  /** `intGoals` */
  readonly goals: number | null;
  /** `strSport` */
  readonly sport: string | null;
}

/**
 * A career milestone or award (`lookupmilestones.php`, `lookup/player_milestones`).
 */
export interface Milestone extends ApiRecord {
  readonly kind: "Milestone";
  /** `id` */
  readonly id: number | null;
  /** `idMilestone` */
  readonly milestoneId: number | null;
  /** `strMilestone` */
  readonly name: string | null;
  /** `dateMilestone` (YYYY-MM-DD) */
  readonly date: string | null;
  /** `idPlayer` */
  readonly playerId: number | null;
  /** `strPlayer` */
  readonly player: string | null;
  /** `idTeam` */
  readonly teamId: number | null;
  /** `strTeam` */
  readonly team: string | null;
  /** `strSport` */
  readonly sport: string | null;
  /** `strMilestoneLogo` */
  readonly logo: string | null;
}

/**
 * A player's contract (`lookupcontracts.php`, `lookup/player_contracts`).
 */
export interface Contract extends ApiRecord {
  readonly kind: "Contract";
  /** `id` */
  readonly id: number | null;
  /** `idPlayer` */
  readonly playerId: number | null;
  /** `strPlayer` */
  readonly player: string | null;
  /** `idTeam` */
  readonly teamId: number | null;
  /** `strTeam` */
  readonly team: string | null;
  /** `strBadge` */
  readonly badge: string | null;
  /** `strYearStart` */
  readonly yearStart: number | null;
  /** `strYearEnd` */
  readonly yearEnd: number | null;
  /** `strWage`, as text */
  readonly wage: string | null;
  /** `strSport` */
  readonly sport: string | null;
}

/**
 * One competitor's result in an individual-sport event: a race, a golf tournament, a
 * fight. Returned both per player (`playerresults.php`) and per event (`eventresults.php`).
 *
 */
export interface EventResult extends ApiRecord {
  readonly kind: "EventResult";
  /** `idResult` */
  readonly id: number | null;
  /** `idEvent` */
  readonly eventId: number | null;
  /** `strEvent` */
  readonly event: string | null;
  /** `dateEvent` (YYYY-MM-DD) */
  readonly date: string | null;
  /** `strSeason` */
  readonly season: string | null;
  /** `strSport` */
  readonly sport: string | null;
  /** `strCountry` */
  readonly country: string | null;
  /** `idPlayer` */
  readonly playerId: number | null;
  /** `strPlayer` */
  readonly player: string | null;
  /** `idTeam` */
  readonly teamId: number | null;
  /** `intPosition`: finishing position */
  readonly position: number | null;
  /** `intPoints` */
  readonly points: number | null;
  /** `strResult`: free text */
  readonly result: string | null;
  /** `strDetail`: e.g. a time gap `+29.520` */
  readonly detail: string | null;
}

/**
 * One statistic for a player in one season (`lookupplayerstats.php`, `lookup/player_stats`).
 */
export interface PlayerStat extends ApiRecord {
  readonly kind: "PlayerStat";
  /** `id` */
  readonly id: number | null;
  /** `idPlayer` */
  readonly playerId: number | null;
  /** `strPlayer` */
  readonly player: string | null;
  /** `idTeam` */
  readonly teamId: number | null;
  /** `strTeam` */
  readonly team: string | null;
  /** `strTeamBadge` */
  readonly teamBadge: string | null;
  /** `idLeague` */
  readonly leagueId: number | null;
  /** `strLeague` */
  readonly league: string | null;
  /** `strLeagueBadge` */
  readonly leagueBadge: string | null;
  /** `strSeason` */
  readonly season: string | null;
  /** `strSport` */
  readonly sport: string | null;
  /** `strStatistic`, e.g. `Goals`, `Appearances`, `Mins Played` */
  readonly statistic: string | null;
  /** `strValue`, as text */
  readonly value: string | null;
  /** `value` as a number, when it is one. */
  readonly numericValue: number | null;
}

/**
 * A team kit (`lookupequipment.php`, `lookup/team_equipment`).
 */
export interface Equipment extends ApiRecord {
  readonly kind: "Equipment";
  /** `idEquipment` */
  readonly id: number | null;
  /** `idTeam` */
  readonly teamId: number | null;
  /** `strSeason` */
  readonly season: string | null;
  /** `strType`, e.g. `1st`, `2nd`, `GK` */
  readonly type: string | null;
  /** `strEquipment`: the image */
  readonly image: string | null;
  /** `strUsername`: who uploaded it */
  readonly uploadedBy: string | null;
  /** `date`: when it was added (zone not stated) (YYYY-MM-DDTHH:MM:SS, zone not stated) */
  readonly added: string | null;
}

/**
 * A stadium, arena or circuit.
 */
export interface Venue extends ApiRecord {
  readonly kind: "Venue";
  /** `idVenue` */
  readonly id: number | null;
  /** `strVenue` */
  readonly name: string | null;
  /** `strVenueAlternate` */
  readonly alternateName: string | null;
  /** `strVenueSponsor` */
  readonly sponsorName: string | null;
  /** `strSport` */
  readonly sport: string | null;
  /** `strLocation` */
  readonly location: string | null;
  /** `strCountry` */
  readonly country: string | null;
  /** `strTimezone`, as text, e.g. `UTC +00:00 Greenwich Mean Time (GMT)` */
  readonly timezone: string | null;
  /** `intCapacity` */
  readonly capacity: number | null;
  /** `intFormedYear` */
  readonly formedYear: number | null;
  /** `strArchitect` */
  readonly architect: string | null;
  /** `strCost`, as text */
  readonly cost: string | null;
  /** `strMap`: either `lat, lon` or an image URL */
  readonly map: string | null;
  /** `strThumb` */
  readonly thumb: string | null;
  /** `strLogo` */
  readonly logo: string | null;
  /** `strFanart1`..`strFanart4` */
  readonly fanart: readonly string[];
  /** `strCreativeCommons`: see [Player.creativeCommons] */
  readonly creativeCommons: boolean | null;
  /** `strDescriptionEN`, ... */
  readonly descriptions: Readonly<Record<string, string>>;
  readonly socials: Socials;
  /** `intLoved` */
  readonly loved: number | null;
  /** `strLocked` */
  readonly isLocked: boolean | null;
  /** `idDupe`: set when this record duplicates another venue */
  readonly duplicateOf: number | null;
  /** The English description. */
  readonly description: string | null;
  /** `map` as [latitude, longitude], when it holds coordinates. */
  readonly coordinates: readonly [number, number] | null;
}

/** Every record type. */
export type AnyRecord = Sport | Country | League | Season | SeasonPoster | Team | Event | Standing | LineupEntry | TimelineEntry | EventStat | TvListing | LiveScore | Player | Honour | FormerTeam | Milestone | Contract | EventResult | PlayerStat | Equipment | Venue;

/** @internal */
export function parseSport(raw: RawRecord): Sport {
  const r = new Rec(raw);
  return Object.freeze({
    kind: "Sport",
    raw,
    id: r.id("idSport"),
    name: r.s("strSport"),
    format: r.s("strFormat"),
    description: r.s("strSportDescription"),
    thumb: r.s("strSportThumb"),
    thumbBlackAndWhite: r.s("strSportThumbBW"),
    icon: r.s("strSportIconGreen"),
  });
}

/** @internal */
export function parseCountry(raw: RawRecord): Country {
  const r = new Rec(raw);
  return Object.freeze({
    kind: "Country",
    raw,
    name: r.s("name_en"),
    nameFr: r.s("name_fr"),
    code: r.s("code"),
    flag16: r.s("flag_url_16"),
    flag32: r.s("flag_url_32"),
    flag64: r.s("flag_url_64"),
    apiFootballId: r.id("idAPIfootball"),
  });
}

/** @internal */
export function parseLeague(raw: RawRecord): League {
  const r = new Rec(raw);
  const descriptions = r.descriptions();
  return Object.freeze({
    kind: "League",
    raw,
    id: r.id("idLeague"),
    name: r.s("strLeague"),
    alternateNames: r.csv("strLeagueAlternate"),
    sport: r.s("strSport"),
    country: r.s("strCountry"),
    gender: r.s("strGender"),
    currentSeason: r.s("strCurrentSeason"),
    division: r.int("intDivision"),
    isCup: r.bool("idCup"),
    formedYear: r.year("intFormedYear"),
    firstEventDate: r.date("dateFirstEvent"),
    isComplete: r.bool("strComplete"),
    eventNaming: r.s("strNaming"),
    tvRights: r.s("strTvRights"),
    badge: r.s("strBadge"),
    logo: r.s("strLogo"),
    banner: r.s("strBanner"),
    poster: r.s("strPoster"),
    trophy: r.s("strTrophy"),
    fanart: r.numbered("strFanart", 4),
    descriptions,
    socials: socials(r),
    isLocked: r.locked(),
    apiFootballId: r.id("idAPIfootball"),
    apiFootballV3Id: r.id("idAPIfootballv3"),
    description: descriptions["EN"] ?? null,
  });
}

/** @internal */
export function parseSeason(raw: RawRecord): Season {
  const r = new Rec(raw);
  return Object.freeze({
    kind: "Season",
    raw,
    name: r.s("strSeason") ?? "",
    badge: r.s("strBadge"),
    poster: r.s("strPoster"),
    description: r.s("strDescriptionEN"),
  });
}

/** @internal */
export function parseSeasonPoster(raw: RawRecord): SeasonPoster {
  const r = new Rec(raw);
  return Object.freeze({
    kind: "SeasonPoster",
    raw,
    id: r.id("idArt"),
    leagueId: r.id("idLeague"),
    season: r.s("strSeason"),
    poster: r.s("strPoster"),
    badge: r.s("strBadge"),
    description: r.s("strDescriptionEN"),
    uploadedBy: r.s("strUsername"),
  });
}

/** @internal */
export function parseTeam(raw: RawRecord): Team {
  const r = new Rec(raw);
  const descriptions = r.descriptions();
  return Object.freeze({
    kind: "Team",
    raw,
    id: r.id("idTeam"),
    name: r.s("strTeam"),
    shortName: r.s("strTeamShort"),
    alternateNames: r.csv("strTeamAlternate"),
    keywords: r.csv("strKeywords"),
    sport: r.s("strSport"),
    gender: r.s("strGender"),
    country: r.s("strCountry"),
    location: r.s("strLocation"),
    formedYear: r.year("intFormedYear"),
    leagueId: r.id("idLeague"),
    league: r.s("strLeague"),
    leagues: leagueRefs(r),
    division: r.s("strDivision"),
    venueId: r.id("idVenue"),
    stadium: r.s("strStadium"),
    colours: r.numbered("strColour", 3),
    badge: r.s("strBadge"),
    logo: r.s("strLogo"),
    banner: r.s("strBanner"),
    equipment: r.s("strEquipment"),
    fanart: r.numbered("strFanart", 4),
    descriptions,
    socials: socials(r),
    loved: r.int("intLoved"),
    isLocked: r.locked(),
    apiFootballId: r.id("idAPIfootball"),
    espnId: r.s("idESPN"),
    description: descriptions["EN"] ?? null,
  });
}

/** @internal */
export function parseEvent(raw: RawRecord): Event {
  const r = new Rec(raw);
  const round = r.int("intRound");
  const statusCode = r.s("strStatus");
  return Object.freeze({
    kind: "Event",
    raw,
    id: r.id("idEvent"),
    name: r.s("strEvent"),
    alternateName: r.s("strEventAlternate"),
    filename: r.s("strFilename"),
    sport: r.s("strSport"),
    leagueId: r.id("idLeague"),
    league: r.s("strLeague"),
    leagueBadge: r.s("strLeagueBadge"),
    season: r.s("strSeason"),
    round,
    group: r.s("strGroup"),
    homeTeamId: r.id("idHomeTeam"),
    homeTeam: r.s("strHomeTeam"),
    homeTeamBadge: r.s("strHomeTeamBadge"),
    awayTeamId: r.id("idAwayTeam"),
    awayTeam: r.s("strAwayTeam"),
    awayTeamBadge: r.s("strAwayTeamBadge"),
    homeScore: r.int("intHomeScore"),
    awayScore: r.int("intAwayScore"),
    homeScoreExtra: r.int("intHomeScoreExtra"),
    awayScoreExtra: r.int("intAwayScoreExtra"),
    timestamp: r.instant("strTimestamp"),
    date: r.date("dateEvent"),
    time: r.time("strTime"),
    localDate: r.date("dateEventLocal"),
    localTime: r.time("strTimeLocal"),
    statusCode,
    isPostponed: r.bool("strPostponed"),
    venueId: r.id("idVenue"),
    venue: r.s("strVenue"),
    city: r.s("strCity"),
    country: r.s("strCountry"),
    spectators: r.int("intSpectators"),
    official: r.s("strOfficial"),
    resultText: r.s("strResult"),
    description: r.s("strDescriptionEN"),
    thumb: r.s("strThumb"),
    poster: r.s("strPoster"),
    banner: r.s("strBanner"),
    square: r.s("strSquare"),
    fanart: r.s("strFanart"),
    map: r.s("strMap"),
    video: r.s("strVideo"),
    tweet: r.s("strTweet1"),
    weather: r.s("strWeather"),
    rating: r.float("intScore"),
    ratingVotes: r.int("intScoreVotes"),
    isLocked: r.locked(),
    apiFootballId: r.id("idAPIfootball"),
    status: eventStatus(statusCode),
    stage: roundStage(round),
  });
}

/** @internal */
export function parseStanding(raw: RawRecord): Standing {
  const r = new Rec(raw);
  return Object.freeze({
    kind: "Standing",
    raw,
    id: r.id("idStanding"),
    rank: r.int("intRank"),
    teamId: r.id("idTeam"),
    team: r.s("strTeam"),
    badge: r.s("strBadge"),
    leagueId: r.id("idLeague"),
    league: r.s("strLeague"),
    season: r.s("strSeason"),
    group: r.s("strGroup"),
    form: r.s("strForm"),
    description: r.s("strDescription"),
    played: r.int("intPlayed"),
    won: r.int("intWin"),
    drawn: r.int("intDraw"),
    lost: r.int("intLoss"),
    goalsFor: r.int("intGoalsFor"),
    goalsAgainst: r.int("intGoalsAgainst"),
    goalDifference: r.int("intGoalDifference"),
    points: r.int("intPoints"),
    updated: r.localDateTime("dateUpdated"),
  });
}

/** @internal */
export function parseLineupEntry(raw: RawRecord): LineupEntry {
  const r = new Rec(raw);
  return Object.freeze({
    kind: "LineupEntry",
    raw,
    id: r.id("idLineup"),
    eventId: r.id("idEvent"),
    event: r.s("strEvent"),
    playerId: r.id("idPlayer"),
    player: r.s("strPlayer"),
    teamId: r.id("idTeam"),
    team: r.s("strTeam"),
    isHome: r.bool("strHome"),
    isSubstitute: r.bool("strSubstitute"),
    position: r.s("strPosition"),
    positionShort: r.s("strPositionShort"),
    formation: r.s("strFormation"),
    squadNumber: r.int("intSquadNumber"),
    country: r.s("strCountry"),
    season: r.s("strSeason"),
    thumb: r.s("strThumb"),
    cutout: r.s("strCutout"),
    render: r.s("strRender"),
    apiFootballId: r.id("idAPIfootball"),
  });
}

/** @internal */
export function parseTimelineEntry(raw: RawRecord): TimelineEntry {
  const r = new Rec(raw);
  return Object.freeze({
    kind: "TimelineEntry",
    raw,
    id: r.id("idTimeline"),
    eventId: r.id("idEvent"),
    event: r.s("strEvent"),
    date: r.date("dateEvent"),
    season: r.s("strSeason"),
    minute: r.int("intTime"),
    period: r.s("strPeriod"),
    type: r.s("strTimeline"),
    detail: r.s("strTimelineDetail"),
    comment: r.s("strComment"),
    playerId: r.id("idPlayer"),
    player: r.s("strPlayer"),
    cutout: r.s("strCutout"),
    assistId: r.id("idAssist"),
    assist: r.s("strAssist"),
    teamId: r.id("idTeam"),
    team: r.s("strTeam"),
    isHome: r.bool("strHome"),
    apiFootballId: r.id("idAPIfootball"),
  });
}

/** @internal */
export function parseEventStat(raw: RawRecord): EventStat {
  const r = new Rec(raw);
  return Object.freeze({
    kind: "EventStat",
    raw,
    id: r.id("idStatistic"),
    eventId: r.id("idEvent"),
    event: r.s("strEvent"),
    name: r.s("strStat"),
    home: r.float("intHome"),
    away: r.float("intAway"),
    apiFootballId: r.id("idApiFootball"),
  });
}

/** @internal */
export function parseTvListing(raw: RawRecord): TvListing {
  const r = new Rec(raw);
  return Object.freeze({
    kind: "TvListing",
    raw,
    id: r.id("id"),
    eventId: r.id("idEvent"),
    event: r.s("strEvent"),
    sport: r.s("strSport"),
    season: r.s("strSeason"),
    channelId: r.id("idChannel"),
    channel: r.s("strChannel"),
    channelLogo: r.s("strLogo"),
    country: r.s("strCountry"),
    eventCountry: r.s("strEventCountry"),
    timestamp: r.instant("strTimeStamp") ?? r.instant("strTimestamp"),
    date: r.date("dateEvent"),
    time: r.time("strTime"),
    division: r.int("intDivision"),
    eventThumb: r.s("strEventThumb"),
    eventPoster: r.s("strEventPoster"),
    eventBanner: r.s("strEventBanner"),
    eventSquare: r.s("strEventSquare"),
  });
}

/** @internal */
export function parseLiveScore(raw: RawRecord): LiveScore {
  const r = new Rec(raw);
  const statusCode = r.s("strStatus");
  return Object.freeze({
    kind: "LiveScore",
    raw,
    id: r.id("idLiveScore"),
    eventId: r.id("idEvent"),
    sport: r.s("strSport"),
    leagueId: r.id("idLeague"),
    league: r.s("strLeague"),
    division: r.int("intDivision"),
    homeTeamId: r.id("idHomeTeam"),
    homeTeam: r.s("strHomeTeam"),
    homeTeamBadge: r.s("strHomeTeamBadge"),
    awayTeamId: r.id("idAwayTeam"),
    awayTeam: r.s("strAwayTeam"),
    awayTeamBadge: r.s("strAwayTeamBadge"),
    homeScore: r.int("intHomeScore"),
    awayScore: r.int("intAwayScore"),
    statusCode,
    progress: r.s("strProgress"),
    eventTime: r.time("strEventTime"),
    date: r.date("dateEvent"),
    timestamp: r.instant("strTimestamp"),
    updated: r.localDateTime("updated"),
    status: eventStatus(statusCode),
  });
}

/** @internal */
export function parsePlayer(raw: RawRecord): Player {
  const r = new Rec(raw);
  const descriptions = r.descriptions();
  return Object.freeze({
    kind: "Player",
    raw,
    id: r.id("idPlayer"),
    name: r.s("strPlayer"),
    alternateName: r.s("strPlayerAlternate"),
    lastName: r.s("strLastName"),
    teamId: r.id("idTeam"),
    team: r.s("strTeam"),
    secondTeamId: r.id("idTeam2"),
    secondTeam: r.s("strTeam2"),
    nationalTeamId: r.id("idTeamNational"),
    managerId: r.id("idPlayerManager"),
    sport: r.s("strSport"),
    nationality: r.s("strNationality"),
    position: r.s("strPosition"),
    number: r.s("strNumber"),
    status: r.s("strStatus"),
    gender: r.s("strGender"),
    born: r.date("dateBorn"),
    birthLocation: r.s("strBirthLocation"),
    died: r.date("dateDied"),
    deathLocation: r.s("strDeathLocation"),
    signed: r.date("dateSigned"),
    signing: r.s("strSigning"),
    wage: r.s("strWage"),
    agent: r.s("strAgent"),
    height: r.s("strHeight"),
    weight: r.s("strWeight"),
    side: r.s("strSide"),
    kit: r.s("strKit"),
    outfitter: r.s("strOutfitter"),
    college: r.s("strCollege"),
    ethnicity: r.s("strEthnicity"),
    thumb: r.s("strThumb"),
    cutout: r.s("strCutout"),
    render: r.s("strRender"),
    cartoon: r.s("strCartoon"),
    banner: r.s("strBanner"),
    poster: r.s("strPoster"),
    fanart: r.numbered("strFanart", 4),
    creativeCommons: r.bool("strCreativeCommons"),
    creativeCommonsAttribution: r.s("strCreativeCommonsAttribution"),
    descriptions,
    socials: socials(r),
    loved: r.int("intLoved"),
    isLocked: r.locked(),
    relevance: r.float("relevance"),
    externalIds: externalIds(r),
    description: descriptions["EN"] ?? null,
  });
}

/** @internal */
export function parseHonour(raw: RawRecord): Honour {
  const r = new Rec(raw);
  return Object.freeze({
    kind: "Honour",
    raw,
    id: r.id("id"),
    honourId: r.id("idHonour"),
    name: r.s("strHonour"),
    season: r.s("strSeason"),
    playerId: r.id("idPlayer"),
    player: r.s("strPlayer"),
    teamId: r.id("idTeam"),
    team: r.s("strTeam"),
    teamBadge: r.s("strTeamBadge"),
    leagueId: r.id("idLeague"),
    sport: r.s("strSport"),
    logo: r.s("strHonourLogo"),
    trophy: r.s("strHonourTrophy"),
  });
}

/** @internal */
export function parseFormerTeam(raw: RawRecord): FormerTeam {
  const r = new Rec(raw);
  return Object.freeze({
    kind: "FormerTeam",
    raw,
    id: r.id("id"),
    playerId: r.id("idPlayer"),
    player: r.s("strPlayer"),
    teamId: r.id("idFormerTeam"),
    team: r.s("strFormerTeam"),
    badge: r.s("strBadge"),
    joined: r.s("strJoined"),
    departed: r.s("strDeparted"),
    moveType: r.s("strMoveType"),
    appearances: r.int("intAppearances"),
    goals: r.int("intGoals"),
    sport: r.s("strSport"),
  });
}

/** @internal */
export function parseMilestone(raw: RawRecord): Milestone {
  const r = new Rec(raw);
  return Object.freeze({
    kind: "Milestone",
    raw,
    id: r.id("id"),
    milestoneId: r.id("idMilestone"),
    name: r.s("strMilestone"),
    date: r.date("dateMilestone"),
    playerId: r.id("idPlayer"),
    player: r.s("strPlayer"),
    teamId: r.id("idTeam"),
    team: r.s("strTeam"),
    sport: r.s("strSport"),
    logo: r.s("strMilestoneLogo"),
  });
}

/** @internal */
export function parseContract(raw: RawRecord): Contract {
  const r = new Rec(raw);
  return Object.freeze({
    kind: "Contract",
    raw,
    id: r.id("id"),
    playerId: r.id("idPlayer"),
    player: r.s("strPlayer"),
    teamId: r.id("idTeam"),
    team: r.s("strTeam"),
    badge: r.s("strBadge"),
    yearStart: r.year("strYearStart"),
    yearEnd: r.year("strYearEnd"),
    wage: r.s("strWage"),
    sport: r.s("strSport"),
  });
}

/** @internal */
export function parseEventResult(raw: RawRecord): EventResult {
  const r = new Rec(raw);
  return Object.freeze({
    kind: "EventResult",
    raw,
    id: r.id("idResult"),
    eventId: r.id("idEvent"),
    event: r.s("strEvent"),
    date: r.date("dateEvent"),
    season: r.s("strSeason"),
    sport: r.s("strSport"),
    country: r.s("strCountry"),
    playerId: r.id("idPlayer"),
    player: r.s("strPlayer"),
    teamId: r.id("idTeam"),
    position: r.int("intPosition"),
    points: r.int("intPoints"),
    result: r.s("strResult"),
    detail: r.s("strDetail"),
  });
}

/** @internal */
export function parsePlayerStat(raw: RawRecord): PlayerStat {
  const r = new Rec(raw);
  const value = r.s("strValue");
  return Object.freeze({
    kind: "PlayerStat",
    raw,
    id: r.id("id"),
    playerId: r.id("idPlayer"),
    player: r.s("strPlayer"),
    teamId: r.id("idTeam"),
    team: r.s("strTeam"),
    teamBadge: r.s("strTeamBadge"),
    leagueId: r.id("idLeague"),
    league: r.s("strLeague"),
    leagueBadge: r.s("strLeagueBadge"),
    season: r.s("strSeason"),
    sport: r.s("strSport"),
    statistic: r.s("strStatistic"),
    value,
    numericValue: numeric(value),
  });
}

/** @internal */
export function parseEquipment(raw: RawRecord): Equipment {
  const r = new Rec(raw);
  return Object.freeze({
    kind: "Equipment",
    raw,
    id: r.id("idEquipment"),
    teamId: r.id("idTeam"),
    season: r.s("strSeason"),
    type: r.s("strType"),
    image: r.s("strEquipment"),
    uploadedBy: r.s("strUsername"),
    added: r.localDateTime("date"),
  });
}

/** @internal */
export function parseVenue(raw: RawRecord): Venue {
  const r = new Rec(raw);
  const map = r.s("strMap");
  const descriptions = r.descriptions();
  return Object.freeze({
    kind: "Venue",
    raw,
    id: r.id("idVenue"),
    name: r.s("strVenue"),
    alternateName: r.s("strVenueAlternate"),
    sponsorName: r.s("strVenueSponsor"),
    sport: r.s("strSport"),
    location: r.s("strLocation"),
    country: r.s("strCountry"),
    timezone: r.s("strTimezone"),
    capacity: r.int("intCapacity"),
    formedYear: r.year("intFormedYear"),
    architect: r.s("strArchitect"),
    cost: r.s("strCost"),
    map,
    thumb: r.s("strThumb"),
    logo: r.s("strLogo"),
    fanart: r.numbered("strFanart", 4),
    creativeCommons: r.bool("strCreativeCommons"),
    descriptions,
    socials: socials(r),
    loved: r.int("intLoved"),
    isLocked: r.locked(),
    duplicateOf: r.id("idDupe"),
    description: descriptions["EN"] ?? null,
    coordinates: coordinates(map),
  });
}
