"""The HTTP layer. Implement ``AsyncTransport`` to use another HTTP stack or to fake the network in tests.

Source of truth for ``_sync/_transport.py`` (generated by ``tools/unasync.py``).
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field
from typing import Protocol

import httpx


@dataclass(frozen=True)
class Response:
    status: int
    body: str
    headers: Mapping[str, str] = field(default_factory=dict)

    def header(self, name: str) -> str | None:
        return next((v for k, v in self.headers.items() if k.lower() == name.lower()), None)


class AsyncTransport(Protocol):
    """Performs GET requests. Raise ``OSError`` (e.g. ``ConnectionError``) for network failures;
    return every HTTP status, including 4xx and 5xx, as a ``Response``."""

    async def get(self, url: str, headers: Mapping[str, str]) -> Response: ...

    async def aclose(self) -> None: ...


class HttpxAsyncTransport:
    """The default transport, on httpx. Pass your own ``httpx.AsyncClient`` to share connections."""

    def __init__(self, client: httpx.AsyncClient | None = None, timeout: float = 30.0) -> None:
        self._owned = client is None
        self._client = client or httpx.AsyncClient(timeout=timeout)

    async def get(self, url: str, headers: Mapping[str, str]) -> Response:
        try:
            r = await self._client.get(url, headers=dict(headers))
        except httpx.TransportError as e:
            raise ConnectionError(str(e) or type(e).__name__) from e
        return Response(r.status_code, r.text, dict(r.headers))

    async def aclose(self) -> None:
        if self._owned:
            await self._client.aclose()
