"""The v1 API: ``https://www.thesportsdb.com/api/v1/json/{key}/{endpoint}.php``.

Works with the free keys (small result limits, noted on each method) and with premium keys
(full results). Names may contain spaces; the library encodes them.

Source of truth for ``_sync/v1.py`` (generated by ``tools/unasync.py``).
"""

from __future__ import annotations

from datetime import date
from typing import TypeVar

from ..cache import Freshness
from ..models import (
    Contract,
    Country,
    Equipment,
    Event,
    EventResult,
    EventStat,
    FormerTeam,
    Honour,
    League,
    LineupEntry,
    LiveScore,
    Milestone,
    Player,
    PlayerStat,
    Season,
    Sport,
    Standing,
    Team,
    TimelineEntry,
    TvListing,
    Venue,
)
from ._requester import AsyncRequester

LIVE, MEDIUM, SLOW, STATIC = Freshness.LIVE, Freshness.MEDIUM, Freshness.SLOW, Freshness.STATIC
T = TypeVar("T")


class AsyncV1Api:
    def __init__(self, r: AsyncRequester) -> None:
        self.search = AsyncV1Search(r)
        self.lookup = AsyncV1Lookup(r)
        self.list = AsyncV1Lists(r)
        self.schedule = AsyncV1Schedule(r)
        self.tv = AsyncV1Tv(r)
        self.video = AsyncV1Video(r)
        self.live = AsyncV1Live(r)


class AsyncV1Search:
    """Search endpoints. Free keys: one result each."""

    def __init__(self, r: AsyncRequester) -> None:
        self._r = r

    async def teams(self, name: str) -> list[Team]:
        """``searchteams.php?t=``: teams by name."""
        return await self._r.v1("searchteams.php", "teams", SLOW, Team._from, t=name)

    async def events(self, name: str, season: str | None = None, date: date | None = None) -> list[Event]:
        """``searchevents.php?e=``: events by name, ``Home vs Away``. Narrow with a season or a date, not both."""
        if season is not None and date is not None:
            raise ValueError("Pass season or date, not both")
        return await self._r.v1("searchevents.php", "event", MEDIUM, Event._from, e=name, s=season, d=date)

    async def events_by_filename(self, filename: str, season: str | None = None) -> list[Event]:
        """``searchfilename.php?e=``: events by ``Event.filename``, e.g. ``English Premier League 2015-04-26 Arsenal vs Chelsea``."""
        return await self._r.v1("searchfilename.php", "event", MEDIUM, Event._from, e=filename, s=season)

    async def players(self, name: str) -> list[Player]:
        """``searchplayers.php?p=``: players by name (summary fields)."""
        return await self._r.v1("searchplayers.php", "player", SLOW, Player._from, p=name)

    async def venues(self, name: str) -> list[Venue]:
        """``searchvenues.php?v=``: venues by name."""
        return await self._r.v1("searchvenues.php", "venues", SLOW, Venue._from, v=name)


class AsyncV1Lookup:
    """Lookups by id."""

    def __init__(self, r: AsyncRequester) -> None:
        self._r = r

    async def league(self, id: int) -> League | None:
        """``lookupleague.php?id=``"""
        return _first(await self._r.v1("lookupleague.php", "leagues", SLOW, League._from, id=id))

    async def table(self, league_id: int, season: str | None = None) -> list[Standing]:
        """``lookuptable.php?l=``: the league table. Free keys: top 5 rows. Only some leagues have tables."""
        return await self._r.v1("lookuptable.php", "table", MEDIUM, Standing._from, l=league_id, s=season)

    async def team(self, id: int) -> Team | None:
        """``lookupteam.php?id=``"""
        return _first(await self._r.v1("lookupteam.php", "teams", SLOW, Team._from, id=id))

    async def equipment(self, team_id: int) -> list[Equipment]:
        """``lookupequipment.php?id=``: a team's kits. Free keys: 2."""
        return await self._r.v1("lookupequipment.php", "equipment", SLOW, Equipment._from, id=team_id)

    async def player(self, id: int) -> Player | None:
        """``lookupplayer.php?id=``"""
        return _first(await self._r.v1("lookupplayer.php", "players", SLOW, Player._from, id=id))

    async def honours(self, player_id: int) -> list[Honour]:
        """``lookuphonours.php?id=``. Free keys: 5."""
        return await self._r.v1("lookuphonours.php", "honours", SLOW, Honour._from, id=player_id)

    async def former_teams(self, player_id: int) -> list[FormerTeam]:
        """``lookupformerteams.php?id=``. Free keys: 5."""
        return await self._r.v1("lookupformerteams.php", "formerteams", SLOW, FormerTeam._from, id=player_id)

    async def milestones(self, player_id: int) -> list[Milestone]:
        """``lookupmilestones.php?id=``. Free keys: 5."""
        return await self._r.v1("lookupmilestones.php", "milestones", SLOW, Milestone._from, id=player_id)

    async def contracts(self, player_id: int) -> list[Contract]:
        """``lookupcontracts.php?id=``. Free keys: 1."""
        return await self._r.v1("lookupcontracts.php", "contracts", SLOW, Contract._from, id=player_id)

    async def player_results(self, player_id: int) -> list[EventResult]:
        """``playerresults.php?id=``: an individual-sport player's results. Free keys: 5."""
        return await self._r.v1("playerresults.php", "results", MEDIUM, EventResult._from, id=player_id)

    async def player_stats(self, player_id: int) -> list[PlayerStat]:
        """``lookupplayerstats.php?id=``. Free keys: 10."""
        return await self._r.v1("lookupplayerstats.php", "playerstats", MEDIUM, PlayerStat._from, id=player_id)

    async def event(self, id: int) -> Event | None:
        """``lookupevent.php?id=``"""
        return _first(await self._r.v1("lookupevent.php", "events", MEDIUM, Event._from, id=id))

    async def event_results(self, event_id: int) -> list[EventResult]:
        """``eventresults.php?id=``: every competitor's result in an individual-sport event. Free keys: 5."""
        return await self._r.v1("eventresults.php", "results", MEDIUM, EventResult._from, id=event_id)

    async def lineup(self, event_id: int) -> list[LineupEntry]:
        """``lookuplineup.php?id=`` (not ``lookuplineups.php``, which is gone). Free keys: 5."""
        return await self._r.v1("lookuplineup.php", "lineup", MEDIUM, LineupEntry._from, id=event_id)

    async def timeline(self, event_id: int) -> list[TimelineEntry]:
        """``lookuptimeline.php?id=``: goals, cards and substitutions. Free keys: 5."""
        return await self._r.v1("lookuptimeline.php", "timeline", MEDIUM, TimelineEntry._from, id=event_id)

    async def event_stats(self, event_id: int) -> list[EventStat]:
        """``lookupeventstats.php?id=``. Free keys: 5."""
        return await self._r.v1("lookupeventstats.php", "eventstats", MEDIUM, EventStat._from, id=event_id)

    async def event_tv(self, event_id: int) -> list[TvListing]:
        """``lookuptv.php?id=``: the channels showing an event. Free keys: 2."""
        return await self._r.v1("lookuptv.php", "tvevent", MEDIUM, TvListing._from, id=event_id)

    async def venue(self, id: int) -> Venue | None:
        """``lookupvenue.php?id=``"""
        return _first(await self._r.v1("lookupvenue.php", "venues", SLOW, Venue._from, id=id))


class AsyncV1Lists:
    """Lists."""

    def __init__(self, r: AsyncRequester) -> None:
        self._r = r

    async def sports(self) -> list[Sport]:
        """``all_sports.php``. Free keys: 2."""
        return await self._r.v1("all_sports.php", "sports", STATIC, Sport._from)

    async def countries(self) -> list[Country]:
        """``all_countries.php``: names and flags. Free keys: 50."""
        return await self._r.v1("all_countries.php", "countries", STATIC, Country._from)

    async def leagues(self) -> list[League]:
        """``all_leagues.php``: id, name, sport (alternate names with a premium key only). Free keys: 5."""
        return await self._r.v1("all_leagues.php", "leagues", STATIC, League._from)

    async def leagues_in_country(self, country: str, sport: str | None = None) -> list[League]:
        """``search_all_leagues.php?c=&s=``: full league records. Note the record key really is ``countries``."""
        return await self._r.v1("search_all_leagues.php", "countries", SLOW, League._from, c=country, s=sport)

    async def seasons(
        self, league_id: int, badges: bool = False, posters: bool = False, descriptions: bool = False
    ) -> list[Season]:
        """``search_all_seasons.php?id=``: season names, plus one of badges, posters or descriptions."""
        if sum((badges, posters, descriptions)) > 1:
            raise ValueError("Ask for one of badges, posters or descriptions per request")
        return await self._r.v1(
            "search_all_seasons.php", "seasons", SLOW, Season._from, id=league_id,
            badge=1 if badges else None, poster=1 if posters else None, description=1 if descriptions else None,
        )

    async def teams_in_league(self, league_name: str) -> list[Team]:
        """``search_all_teams.php?l=``: a league's teams, by league **name**. Free keys: 10.

        Not ``lookup_all_teams.php?id=``, which returns another league's teams.
        """
        return await self._r.v1("search_all_teams.php", "teams", SLOW, Team._from, l=league_name)

    async def teams_in_country(self, sport: str, country: str) -> list[Team]:
        """``search_all_teams.php?s=&c=``. Free keys: 10."""
        return await self._r.v1("search_all_teams.php", "teams", SLOW, Team._from, s=sport, c=country)

    async def players(self, team_id: int) -> list[Player]:
        """``lookup_all_players.php?id=``: a team's squad. Free keys: 10."""
        return await self._r.v1("lookup_all_players.php", "player", SLOW, Player._from, id=team_id)


class AsyncV1Schedule:
    """Schedules and results. Event times are UTC."""

    def __init__(self, r: AsyncRequester) -> None:
        self._r = r

    async def team_next(self, team_id: int) -> list[Event]:
        """``eventsnext.php?id=``. Free keys: 1, home games only."""
        return await self._r.v1("eventsnext.php", "events", MEDIUM, Event._from, id=team_id)

    async def team_last(self, team_id: int) -> list[Event]:
        """``eventslast.php?id=``. Free keys: 1, home games only. (The record key is ``results``.)"""
        return await self._r.v1("eventslast.php", "results", MEDIUM, Event._from, id=team_id)

    async def league_next(self, league_id: int) -> list[Event]:
        """``eventsnextleague.php?id=``. Free keys: 1."""
        return await self._r.v1("eventsnextleague.php", "events", MEDIUM, Event._from, id=league_id)

    async def league_past(self, league_id: int) -> list[Event]:
        """``eventspastleague.php?id=``. Free keys: 1."""
        return await self._r.v1("eventspastleague.php", "events", MEDIUM, Event._from, id=league_id)

    async def day(
        self, date: date, sport: str | None = None, league_id: int | None = None, league_name: str | None = None
    ) -> list[Event]:
        """``eventsday.php?d=``: every event on a UTC day, optionally for one sport or league. Free keys: 3."""
        if league_id is not None and league_name is not None:
            raise ValueError("Pass league_id or league_name, not both")
        league = league_id if league_id is not None else league_name
        return await self._r.v1("eventsday.php", "events", MEDIUM, Event._from, d=date, s=sport, l=league)

    async def season(self, league_id: int, season: str) -> list[Event]:
        """``eventsseason.php?id=&s=``: a whole season (premium). Free keys: 5."""
        return await self._r.v1("eventsseason.php", "events", MEDIUM, Event._from, id=league_id, s=season)

    async def round(self, league_id: int, round: int, season: str) -> list[Event]:
        """``eventsround.php?id=&r=&s=``: one round. **Undocumented and free keys only**: premium keys
        get HTTP 404. ``helpers.round_events`` picks the right route for any key."""
        return await self._r.v1("eventsround.php", "events", MEDIUM, Event._from, id=league_id, r=round, s=season)


class AsyncV1Tv:
    """TV listings. Free keys: 1 per call."""

    def __init__(self, r: AsyncRequester) -> None:
        self._r = r

    async def day(self, date: date, sport: str | None = None, country: str | None = None) -> list[TvListing]:
        """``eventstv.php?d=``: listings for a day, optionally for a sport, or a country **and** sport.
        The API returns an empty body for a country without a sport, so that is rejected here."""
        if country is not None and sport is None:
            raise ValueError("eventstv.php needs a sport when filtering by country")
        return await self._r.v1("eventstv.php", "tvevents", MEDIUM, TvListing._from, d=date, a=country, s=sport)

    async def channel(self, name: str) -> list[TvListing]:
        """``eventstv.php?c=``: upcoming listings on a channel, by name (e.g. ``TSN 1``)."""
        return await self._r.v1("eventstv.php", "tvevents", MEDIUM, TvListing._from, c=name)

    async def channel_id(self, channel_id: int) -> list[TvListing]:
        """``eventstv.php?id=``: by **channel** id (``TvListing.channel_id``), not event id."""
        return await self._r.v1("eventstv.php", "tvevents", MEDIUM, TvListing._from, id=channel_id)


class AsyncV1Video:
    def __init__(self, r: AsyncRequester) -> None:
        self._r = r

    async def highlights(self, date: date, league_id: int | None = None, sport: str | None = None) -> list[Event]:
        """``eventshighlights.php?d=``: events with highlight videos (``Event.video``). Free keys: 2."""
        return await self._r.v1("eventshighlights.php", "tvhighlights", MEDIUM, Event._from, d=date, l=league_id, s=sport)


class AsyncV1Live:
    """Live scores on v1: **undocumented** but answering, including with free keys (the full feed)."""

    def __init__(self, r: AsyncRequester) -> None:
        self._r = r

    async def sport(self, sport: str) -> list[LiveScore]:
        """``livescore.php?s=``. (``l=`` is ignored by the API, so it isn't offered.)"""
        return await self._r.v1("livescore.php", "livescore", LIVE, LiveScore._from, s=sport)


def _first(items: list[T]) -> T | None:
    return items[0] if items else None
