#!/usr/bin/env python3
"""Generates the blocking client (src/thesportsdb_client/_sync/) from the async source (src/thesportsdb_client/_async/).

    python tools/unasync.py          # regenerate
    python tools/unasync.py --check  # exit 1 if _sync/ is out of date (used by the tests)

_compat.py is hand-written on both sides and never generated.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent / "src" / "thesportsdb_client"
SRC, DST = ROOT / "_async", ROOT / "_sync"
SKIP = {"_compat.py", "__init__.py"}

RULES: list[tuple[str, str]] = [
    (r"\basync def ", "def "),
    (r"\basync with ", "with "),
    (r"\basync for ", "for "),
    (r"\bawait ", ""),
    (r"\b[Aa]synchronous\b", "blocking"),
    (r"\bhttpx\.AsyncClient\b", "httpx.Client"),
    (r"\bHttpxAsyncTransport\b", "HttpxTransport"),
    (r"\bAsync(?=[A-Z])", ""),
    (r"\b__aenter__\b", "__enter__"),
    (r"\b__aexit__\b", "__exit__"),
    (r"\baclose\b", "close"),
    (r"Awaitable\[((?:[^\[\]]|\[[^\[\]]*\])*)\]", r"\1"),
    (r"(from collections\.abc import [^\n]*?)\bAwaitable, ", r"\1"),
    (r"(from collections\.abc import [^\n]*?), Awaitable\b", r"\1"),
    (r"Source of truth for ``_sync/(\w+\.py)`` \(generated by ``tools/unasync\.py``\)\.",
     r"GENERATED from ``_async/\1`` by ``tools/unasync.py``. Do not edit."),
    (r"\bSource of truth for ``_sync/(\w+\.py)``[^\n]*", r"GENERATED from ``_async/\1`` by ``tools/unasync.py``. Do not edit."),
]

HEADER = "# GENERATED by tools/unasync.py from src/thesportsdb_client/_async/{name}. Do not edit; edit the async source.\n"


def convert(text: str) -> str:
    for pattern, repl in RULES:
        text = re.sub(pattern, repl, text)
    return text


def expected() -> dict[Path, str]:
    return {DST / f.name: HEADER.format(name=f.name) + convert(f.read_text())
            for f in sorted(SRC.glob("*.py")) if f.name not in SKIP}


def main() -> int:
    files = expected()
    if "--check" in sys.argv:
        stale = [p.name for p, text in files.items() if not p.exists() or p.read_text() != text]
        if stale:
            print("out of date: " + ", ".join(stale) + " (run python tools/unasync.py)")
            return 1
        return 0
    for path, text in files.items():
        path.write_text(text)
    print(f"wrote {len(files)} files to {DST.relative_to(ROOT.parent.parent)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
