# GENERATED by tools/unasync.py from src/sportsdb/_async/_transport.py. Do not edit; edit the async source.
"""The HTTP layer. Implement ``Transport`` to use another HTTP stack or to fake the network in tests.

GENERATED from ``_async/_transport.py`` by ``tools/unasync.py``. Do not edit.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field
from typing import Protocol

import httpx


@dataclass(frozen=True)
class Response:
    status: int
    body: str
    headers: Mapping[str, str] = field(default_factory=dict)

    def header(self, name: str) -> str | None:
        return next((v for k, v in self.headers.items() if k.lower() == name.lower()), None)


class Transport(Protocol):
    """Performs GET requests. Raise ``OSError`` (e.g. ``ConnectionError``) for network failures;
    return every HTTP status, including 4xx and 5xx, as a ``Response``."""

    def get(self, url: str, headers: Mapping[str, str]) -> Response: ...

    def close(self) -> None: ...


class HttpxTransport:
    """The default transport, on httpx. Pass your own ``httpx.Client`` to share connections."""

    def __init__(self, client: httpx.Client | None = None, timeout: float = 30.0) -> None:
        self._owned = client is None
        self._client = client or httpx.Client(timeout=timeout)

    def get(self, url: str, headers: Mapping[str, str]) -> Response:
        try:
            r = self._client.get(url, headers=dict(headers))
        except httpx.TransportError as e:
            raise ConnectionError(str(e) or type(e).__name__) from e
        return Response(r.status_code, r.text, dict(r.headers))

    def close(self) -> None:
        if self._owned:
            self._client.close()
