# GENERATED by tools/unasync.py from src/sportsdb/_async/client.py. Do not edit; edit the async source.
"""The blocking client.

GENERATED from ``_async/client.py`` by ``tools/unasync.py``. Do not edit.
"""

from __future__ import annotations

from collections.abc import Callable
from types import TracebackType
from typing import Any

from ..cache import CachePolicy, ResponseCache
from ..config import FREE_API_KEY, Config
from ..errors import InvalidApiKeyError
from ..events import RequestEvent
from ._requester import Requester
from ._transport import Transport, HttpxTransport
from .helpers import Helpers
from .v1 import V1Api
from .v2 import V2Api


class SportsDB:
    """The blocking TheSportsDB client.

    .. code-block:: python

        with SportsDB() as db:                    # free key 123: v1 only
            arsenal = db.v1.lookup.team(133604)
        with SportsDB(api_key=key) as db:         # premium: v1 and v2
            tv = db.v2.tv.country("Canada")

    One client is safe to share across tasks; its rate limiter, cache and de-duplication cover
    every call made through it. Create one per key and reuse it.
    """

    def __init__(
        self,
        api_key: str = FREE_API_KEY,
        *,
        transport: Transport | None = None,
        requests_per_minute: int | None = None,
        max_retries: int = 2,
        retry_backoff: float = 0.5,
        retry_on_rate_limit: bool = True,
        rate_limit_wait: float = 60.0,
        cache: ResponseCache | None = None,
        cache_policy: CachePolicy | None = None,
        timeout: float = 30.0,
        deduplicate_requests: bool = True,
        request_listener: Callable[[RequestEvent], None] | None = None,
        base_url: str = "https://www.thesportsdb.com",
        user_agent: str = "sportsdb-python",
    ) -> None:
        options: dict[str, Any] = dict(
            api_key=api_key, requests_per_minute=requests_per_minute, max_retries=max_retries,
            retry_backoff=retry_backoff, retry_on_rate_limit=retry_on_rate_limit, rate_limit_wait=rate_limit_wait,
            cache=cache, timeout=timeout, deduplicate_requests=deduplicate_requests,
            request_listener=request_listener, base_url=base_url, user_agent=user_agent,
        )
        if cache_policy is not None:
            options["cache_policy"] = cache_policy
        self.config = Config(**options)
        self._owns_transport = transport is None
        self._transport = transport or HttpxTransport(timeout=timeout)
        requester = Requester(self.config, self._transport)
        self.v1 = V1Api(requester)
        """The v1 API (free and premium keys)."""
        self.v2 = V2Api(requester)
        """The v2 API (premium keys only)."""
        self.helpers = Helpers(self)
        """Common tasks in one call, using v2 or v1 depending on the key."""

    def is_premium_key(self) -> bool:
        """Whether v2 accepts the key. One call (v2 ``lookup/league/4328``) unless it's a free key."""
        if self.config.is_free_key:
            return False
        try:
            self.v2.lookup.league(4328)
            return True
        except InvalidApiKeyError:
            return False

    def close(self) -> None:
        """Closes the HTTP connections the client opened (not a transport you passed in)."""
        if self._owns_transport:
            self._transport.close()

    def __enter__(self) -> SportsDB:
        return self

    def __exit__(
        self, exc_type: type[BaseException] | None, exc: BaseException | None, tb: TracebackType | None
    ) -> None:
        self.close()
