# GENERATED by tools/unasync.py from src/sportsdb/_async/v2.py. Do not edit; edit the async source.
"""The v2 API: ``https://www.thesportsdb.com/api/v2/json/{group}/{name}/{param}``, key in the
``X-API-KEY`` header. **Premium keys only**: with a free key every call raises
``PremiumRequiredError`` without touching the network.

GENERATED from ``_async/v2.py`` by ``tools/unasync.py``. Do not edit.
"""

from __future__ import annotations

from datetime import date
from typing import TypeVar

from ..cache import Freshness
from ..models import (
    Contract,
    Country,
    Equipment,
    Event,
    EventResult,
    EventStat,
    FormerTeam,
    Honour,
    League,
    LineupEntry,
    LiveScore,
    Milestone,
    Player,
    PlayerStat,
    Season,
    Sport,
    Team,
    TimelineEntry,
    TvListing,
    Venue,
)
from ._requester import Requester

LIVE, MEDIUM, SLOW, STATIC = Freshness.LIVE, Freshness.MEDIUM, Freshness.SLOW, Freshness.STATIC
T = TypeVar("T")


class V2Api:
    def __init__(self, r: Requester) -> None:
        self.search = V2Search(r)
        self.lookup = V2Lookup(r)
        self.list = V2Lists(r)
        self.all = V2All(r)
        self.schedule = V2Schedule(r)
        self.tv = V2Tv(r)
        self.live = V2Live(r)


class V2Search:
    """``search/...``: up to about 10 results, summary fields only. Ids arrive as JSON numbers here."""

    def __init__(self, r: Requester) -> None:
        self._r = r

    def leagues(self, name: str) -> list[League]:
        return self._r.v2("search", SLOW, League._from, "search", "league", name)

    def teams(self, name: str) -> list[Team]:
        return self._r.v2("search", SLOW, Team._from, "search", "team", name)

    def players(self, name: str) -> list[Player]:
        return self._r.v2("search", SLOW, Player._from, "search", "player", name)

    def events(self, name: str) -> list[Event]:
        """Needs the exact stored event name; a loose ``Arsenal vs Chelsea`` finds nothing."""
        return self._r.v2("search", MEDIUM, Event._from, "search", "event", name)

    def venues(self, name: str) -> list[Venue]:
        return self._r.v2("search", SLOW, Venue._from, "search", "venue", name)


class V2Lookup:
    """``lookup/...``: full records by id."""

    def __init__(self, r: Requester) -> None:
        self._r = r

    def league(self, id: int) -> League | None:
        return _first(self._r.v2("lookup", SLOW, League._from, "lookup", "league", id))

    def team(self, id: int) -> Team | None:
        return _first(self._r.v2("lookup", SLOW, Team._from, "lookup", "team", id))

    def team_equipment(self, team_id: int) -> list[Equipment]:
        return self._r.v2("lookup", SLOW, Equipment._from, "lookup", "team_equipment", team_id)

    def player(self, id: int) -> Player | None:
        return _first(self._r.v2("lookup", SLOW, Player._from, "lookup", "player", id))

    def player_contracts(self, player_id: int) -> list[Contract]:
        return self._r.v2("lookup", SLOW, Contract._from, "lookup", "player_contracts", player_id)

    def player_results(self, player_id: int) -> list[EventResult]:
        return self._r.v2("lookup", MEDIUM, EventResult._from, "lookup", "player_results", player_id)

    def player_honours(self, player_id: int) -> list[Honour]:
        return self._r.v2("lookup", SLOW, Honour._from, "lookup", "player_honours", player_id)

    def player_milestones(self, player_id: int) -> list[Milestone]:
        return self._r.v2("lookup", SLOW, Milestone._from, "lookup", "player_milestones", player_id)

    def player_teams(self, player_id: int) -> list[FormerTeam]:
        """A player's former teams (v1 calls these ``formerteams``)."""
        return self._r.v2("lookup", SLOW, FormerTeam._from, "lookup", "player_teams", player_id)

    def player_stats(self, player_id: int) -> list[PlayerStat]:
        return self._r.v2("lookup", MEDIUM, PlayerStat._from, "lookup", "player_stats", player_id)

    def event(self, id: int) -> Event | None:
        return _first(self._r.v2("lookup", MEDIUM, Event._from, "lookup", "event", id))

    def event_lineup(self, event_id: int) -> list[LineupEntry]:
        return self._r.v2("lookup", MEDIUM, LineupEntry._from, "lookup", "event_lineup", event_id)

    def event_results(self, event_id: int) -> list[EventResult]:
        return self._r.v2("lookup", MEDIUM, EventResult._from, "lookup", "event_results", event_id)

    def event_stats(self, event_id: int) -> list[EventStat]:
        return self._r.v2("lookup", MEDIUM, EventStat._from, "lookup", "event_stats", event_id)

    def event_timeline(self, event_id: int) -> list[TimelineEntry]:
        return self._r.v2("lookup", MEDIUM, TimelineEntry._from, "lookup", "event_timeline", event_id)

    def event_tv(self, event_id: int) -> list[TvListing]:
        """The channels showing an event."""
        return self._r.v2("lookup", MEDIUM, TvListing._from, "lookup", "event_tv", event_id)

    def event_highlights(self, event_id: int) -> list[Event]:
        """An event with its highlight video in ``Event.video``."""
        return self._r.v2("lookup", MEDIUM, Event._from, "lookup", "event_highlights", event_id)

    def venue(self, id: int) -> Venue | None:
        return _first(self._r.v2("lookup", SLOW, Venue._from, "lookup", "venue", id))


class V2Lists:
    """``list/...``"""

    def __init__(self, r: Requester) -> None:
        self._r = r

    def teams(self, league_id: int) -> list[Team]:
        """A league's teams with badges and colours, but no alternate names (look teams up by id for those)."""
        return self._r.v2("list", SLOW, Team._from, "list", "teams", league_id)

    def seasons(self, league_id: int) -> list[Season]:
        return self._r.v2("list", SLOW, Season._from, "list", "seasons", league_id)

    def players(self, team_id: int) -> list[Player]:
        return self._r.v2("list", SLOW, Player._from, "list", "players", team_id)


class V2All:
    """``all/...``: complete catalogues."""

    def __init__(self, r: Requester) -> None:
        self._r = r

    def countries(self) -> list[Country]:
        return self._r.v2("all", STATIC, Country._from, "all", "countries")

    def sports(self) -> list[Sport]:
        return self._r.v2("all", STATIC, Sport._from, "all", "sports")

    def leagues(self) -> list[League]:
        return self._r.v2("all", STATIC, League._from, "all", "leagues")


class V2Schedule:
    """``schedule/...``. Event times are UTC."""

    def __init__(self, r: Requester) -> None:
        self._r = r

    def league_next(self, league_id: int) -> list[Event]:
        return self._get("next", "league", league_id)

    def league_previous(self, league_id: int) -> list[Event]:
        return self._get("previous", "league", league_id)

    def team_next(self, team_id: int) -> list[Event]:
        return self._get("next", "team", team_id)

    def team_previous(self, team_id: int) -> list[Event]:
        return self._get("previous", "team", team_id)

    def venue_next(self, venue_id: int) -> list[Event]:
        return self._get("next", "venue", venue_id)

    def venue_previous(self, venue_id: int) -> list[Event]:
        return self._get("previous", "venue", venue_id)

    def team_full(self, team_id: int) -> list[Event]:
        """A team's whole schedule, past and future, across all competitions."""
        return self._get("full", "team", team_id)

    def league_season(self, league_id: int, season: str) -> list[Event]:
        """A league's whole season in one call. The current season name is ``League.current_season``."""
        return self._get("league", league_id, season)

    def _get(self, *path: object) -> list[Event]:
        return self._r.v2("schedule", MEDIUM, Event._from, "schedule", *path)


class V2Tv:
    """``filter/tv/...``"""

    def __init__(self, r: Requester) -> None:
        self._r = r

    def day(self, date: date) -> list[TvListing]:
        """Every listing worldwide on a day."""
        return self._get("day", date)

    def country(self, country: str) -> list[TvListing]:
        """About a week of listings for a country, e.g. ``Canada``."""
        return self._get("country", country)

    def sport(self, sport: str) -> list[TvListing]:
        return self._get("sport", sport)

    def channel(self, name: str) -> list[TvListing]:
        """By channel name, in the API's spelling (``TSN 1``, not ``TSN1``); partial names match."""
        return self._get("channel", name)

    def channel_id(self, channel_id: int) -> list[TvListing]:
        return self._get("channelid", channel_id)

    def _get(self, kind: str, value: object) -> list[TvListing]:
        return self._r.v2("filter", MEDIUM, TvListing._from, "filter", "tv", kind, value)


class V2Live:
    """``livescore/...``. Not cached unless the cache policy says so. Entries can be stale."""

    def __init__(self, r: Requester) -> None:
        self._r = r

    def sport(self, sport: str) -> list[LiveScore]:
        return self._r.v2("livescore", LIVE, LiveScore._from, "livescore", sport)

    def league(self, league_id: int) -> list[LiveScore]:
        return self._r.v2("livescore", LIVE, LiveScore._from, "livescore", league_id)

    def all(self) -> list[LiveScore]:
        return self._r.v2("livescore", LIVE, LiveScore._from, "livescore", "all")


def _first(items: list[T]) -> T | None:
    return items[0] if items else None
