// GENERATED by tools/gen-futures.py from V1Api.kt and V2Api.kt. Do not edit by hand.
package io.github.rohang27.thesportsdb

import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.future.future
import io.github.rohang27.thesportsdb.model.*
import java.time.LocalDate
import java.time.ZoneId
import java.time.ZoneOffset
import java.util.concurrent.CompletableFuture

/**
 * A Java-friendly wrapper: every [SportsDbClient] method, returning a [CompletableFuture].
 *
 * ```java
 * SportsDbConfig config = new SportsDbConfig();
 * config.setApiKey(System.getenv("THESPORTSDB_API_KEY"));
 * try (SportsDbFutures db = new SportsDbFutures(config)) {
 *     Team team = db.v1().lookup().team(133604).join();
 *     db.v2().schedule().leagueNext(4328).thenAccept(events -> ...);
 * }
 * ```
 *
 * Single lookups complete with `null` when nothing is found. Failures complete the future
 * exceptionally with a [SportsDbException] (wrapped in `CompletionException` by `join()`).
 * [close] cancels calls still running.
 */
public class SportsDbFutures(
    /** The underlying client, for Kotlin callers or for sharing its cache and rate limiter. */
    public val client: SportsDbClient,
    private val scope: CoroutineScope,
) : AutoCloseable {
    public constructor(client: SportsDbClient) : this(client, CoroutineScope(SupervisorJob() + Dispatchers.IO))
    public constructor(config: SportsDbConfig) : this(SportsDbClient(config))
    public constructor() : this(SportsDbConfig())

    @get:JvmName("v1") public val v1: V1 = V1()
    @get:JvmName("v2") public val v2: V2 = V2()
    @get:JvmName("helpers") public val helpers: HelpersFutures = HelpersFutures()

    /** See [SportsDbClient.isPremiumKey]. */
    public fun isPremiumKey(): CompletableFuture<Boolean> = scope.future { client.isPremiumKey() }

    override fun close(): Unit = scope.cancel()

    private fun <T> call(block: suspend () -> T): CompletableFuture<T> = scope.future { block() }

    /** CompletableFuture versions of [V1Api]. */
    public inner class V1 internal constructor() {
        @get:JvmName("search") public val search: V1Search = V1Search()
        @get:JvmName("lookup") public val lookup: V1Lookup = V1Lookup()
        @get:JvmName("list") public val list: V1Lists = V1Lists()
        @get:JvmName("schedule") public val schedule: V1Schedule = V1Schedule()
        @get:JvmName("tv") public val tv: V1Tv = V1Tv()
        @get:JvmName("video") public val video: V1Video = V1Video()
        @get:JvmName("live") public val live: V1Live = V1Live()
    }

    /** CompletableFuture versions of [V1Api.Search]. */
    public inner class V1Search internal constructor() {
        /** `searchteams.php?t=` — teams by name. Premium returns many matches (15 for "Arsenal"). */
        public fun teams(name: String): CompletableFuture<List<Team>> =
            call { client.v1.search.teams(name) }

        /**
         * `searchevents.php?e=` — events by name, `Home vs Away`. Narrow with a [season]
         * (`2016-2017`) or a [date]; pass at most one of them.
         */
        @JvmOverloads public fun events(name: String, season: String? = null, date: LocalDate? = null): CompletableFuture<List<Event>> =
            call { client.v1.search.events(name, season, date) }

        /**
         * `searchfilename.php?e=` — events by their [Event.filename], e.g.
         * `English Premier League 2015-04-26 Arsenal vs Chelsea`.
         */
        @JvmOverloads public fun eventsByFilename(filename: String, season: String? = null): CompletableFuture<List<Event>> =
            call { client.v1.search.eventsByFilename(filename, season) }

        /** `searchplayers.php?p=` — players by name. Fills only a summary of each player. */
        public fun players(name: String): CompletableFuture<List<Player>> =
            call { client.v1.search.players(name) }

        /** `searchvenues.php?v=` — venues by name. */
        public fun venues(name: String): CompletableFuture<List<Venue>> =
            call { client.v1.search.venues(name) }
    }

    /** CompletableFuture versions of [V1Api.Lookup]. */
    public inner class V1Lookup internal constructor() {
        /** `lookupleague.php?id=` */
        public fun league(id: Long): CompletableFuture<League?> =
            call { client.v1.lookup.league(id) }

        /**
         * `lookuptable.php?l=` — the league table. Free key: top 5 rows. Only some leagues
         * have tables (mostly featured soccer leagues). Omit [season] for the current one.
         */
        @JvmOverloads public fun table(leagueId: Long, season: String? = null): CompletableFuture<List<Standing>> =
            call { client.v1.lookup.table(leagueId, season) }

        /** `lookupteam.php?id=` */
        public fun team(id: Long): CompletableFuture<Team?> =
            call { client.v1.lookup.team(id) }

        /** `lookupequipment.php?id=` — a team's kits over the seasons. Free key: 2. */
        public fun equipment(teamId: Long): CompletableFuture<List<Equipment>> =
            call { client.v1.lookup.equipment(teamId) }

        /** `lookupplayer.php?id=` */
        public fun player(id: Long): CompletableFuture<Player?> =
            call { client.v1.lookup.player(id) }

        /** `lookuphonours.php?id=` — a player's trophies. Free key: 5. */
        public fun honours(playerId: Long): CompletableFuture<List<Honour>> =
            call { client.v1.lookup.honours(playerId) }

        /** `lookupformerteams.php?id=` — a player's previous teams. Free key: 5. */
        public fun formerTeams(playerId: Long): CompletableFuture<List<FormerTeam>> =
            call { client.v1.lookup.formerTeams(playerId) }

        /** `lookupmilestones.php?id=` — a player's milestones and awards. Free key: 5. */
        public fun milestones(playerId: Long): CompletableFuture<List<Milestone>> =
            call { client.v1.lookup.milestones(playerId) }

        /** `lookupcontracts.php?id=` — a player's contracts. Free key: 1. */
        public fun contracts(playerId: Long): CompletableFuture<List<Contract>> =
            call { client.v1.lookup.contracts(playerId) }

        /** `playerresults.php?id=` — an individual-sport player's results. Free key: 5. */
        public fun playerResults(playerId: Long): CompletableFuture<List<EventResult>> =
            call { client.v1.lookup.playerResults(playerId) }

        /** `lookupplayerstats.php?id=` — a player's season statistics. Free key: 10. */
        public fun playerStats(playerId: Long): CompletableFuture<List<PlayerStat>> =
            call { client.v1.lookup.playerStats(playerId) }

        /** `lookupevent.php?id=` */
        public fun event(id: Long): CompletableFuture<Event?> =
            call { client.v1.lookup.event(id) }

        /** `eventresults.php?id=` — every competitor's result in an individual-sport event. Free key: 5. */
        public fun eventResults(eventId: Long): CompletableFuture<List<EventResult>> =
            call { client.v1.lookup.eventResults(eventId) }

        /** `lookuplineup.php?id=` — an event's lineups. Free key: 5. */
        public fun lineup(eventId: Long): CompletableFuture<List<LineupEntry>> =
            call { client.v1.lookup.lineup(eventId) }

        /** `lookuptimeline.php?id=` — goals, cards and substitutions. Free key: 5. */
        public fun timeline(eventId: Long): CompletableFuture<List<TimelineEntry>> =
            call { client.v1.lookup.timeline(eventId) }

        /** `lookupeventstats.php?id=` — team statistics for an event. Free key: 5. */
        public fun eventStats(eventId: Long): CompletableFuture<List<EventStat>> =
            call { client.v1.lookup.eventStats(eventId) }

        /** `lookuptv.php?id=` — the channels showing an event. Free key: 2. */
        public fun eventTv(eventId: Long): CompletableFuture<List<TvListing>> =
            call { client.v1.lookup.eventTv(eventId) }

        /** `lookupvenue.php?id=` */
        public fun venue(id: Long): CompletableFuture<Venue?> =
            call { client.v1.lookup.venue(id) }
    }

    /** CompletableFuture versions of [V1Api.Lists]. */
    public inner class V1Lists internal constructor() {
        /** `all_sports.php`. Free key: 2. */
        public fun sports(): CompletableFuture<List<Sport>> =
            call { client.v1.list.sports() }

        /** `all_countries.php`: names and flags. Free key: 50. */
        public fun countries(): CompletableFuture<List<Country>> =
            call { client.v1.list.countries() }

        /** `all_leagues.php`: id, name and sport (plus alternate names with a premium key). Free key: 5. */
        public fun leagues(): CompletableFuture<List<League>> =
            call { client.v1.list.leagues() }

        /**
         * `search_all_leagues.php?c=&s=` — full league records in a country, optionally for
         * one sport. Free key: 5–10.
         */
        @JvmOverloads public fun leagues(country: String, sport: String? = null): CompletableFuture<List<League>> =
            call { client.v1.list.leagues(country, sport) }

        /**
         * `search_all_seasons.php?id=` — a league's seasons. Season names alone unless you
         * ask for [badges], [posters] or [descriptions] (one per request). Free key: 5.
         */
        @JvmOverloads public fun seasons(leagueId: Long, badges: Boolean = false, posters: Boolean = false, descriptions: Boolean = false): CompletableFuture<List<Season>> =
            call { client.v1.list.seasons(leagueId, badges, posters, descriptions) }

        /** `search_all_teams.php?l=` — every team in a league, by league **name**. Free key: 10. */
        public fun teamsInLeague(leagueName: String): CompletableFuture<List<Team>> =
            call { client.v1.list.teamsInLeague(leagueName) }

        /** `search_all_teams.php?s=&c=` — every team of a sport in a country. Free key: 10. */
        public fun teamsInCountry(sport: String, country: String): CompletableFuture<List<Team>> =
            call { client.v1.list.teamsInCountry(sport, country) }

        /** `lookup_all_players.php?id=` — a team's squad. Free key: 10. */
        public fun players(teamId: Long): CompletableFuture<List<Player>> =
            call { client.v1.list.players(teamId) }
    }

    /** CompletableFuture versions of [V1Api.Schedule]. */
    public inner class V1Schedule internal constructor() {
        /** `eventsnext.php?id=` — a team's next events. Free key: 1, and home games only. */
        public fun teamNext(teamId: Long): CompletableFuture<List<Event>> =
            call { client.v1.schedule.teamNext(teamId) }

        /** `eventslast.php?id=` — a team's last results. Free key: 1, and home games only. */
        public fun teamLast(teamId: Long): CompletableFuture<List<Event>> =
            call { client.v1.schedule.teamLast(teamId) }

        /** `eventsnextleague.php?id=` — a league's next events. Free key: 1. */
        public fun leagueNext(leagueId: Long): CompletableFuture<List<Event>> =
            call { client.v1.schedule.leagueNext(leagueId) }

        /** `eventspastleague.php?id=` — a league's latest results. Free key: 1. */
        public fun leaguePast(leagueId: Long): CompletableFuture<List<Event>> =
            call { client.v1.schedule.leaguePast(leagueId) }

        /**
         * `eventsday.php?d=` — every event on a (UTC) day, optionally for one [sport] or one
         * league ([leagueId] or [leagueName]). Free key: 3. Premium: the whole day (900+).
         */
        @JvmOverloads public fun day(date: LocalDate, sport: String? = null, leagueId: Long? = null, leagueName: String? = null): CompletableFuture<List<Event>> =
            call { client.v1.schedule.day(date, sport, leagueId, leagueName) }

        /**
         * `eventsround.php?id=&r=&s=` — every event in one round (matchday) of a season.
         * **Undocumented, and free keys only:** it answers the free keys (a whole round, e.g. 10
         * games) but returns HTTP 404 to premium keys. With a premium key, use
         * [SportsDbClient.helpers]' `roundEvents`, which filters the v2 season instead.
         */
        public fun round(leagueId: Long, round: Int, season: String): CompletableFuture<List<Event>> =
            call { client.v1.schedule.round(leagueId, round, season) }

        /** `eventsseason.php?id=&s=` — a whole season in one call (premium). Free key: 5–15. */
        public fun season(leagueId: Long, season: String): CompletableFuture<List<Event>> =
            call { client.v1.schedule.season(leagueId, season) }
    }

    /** CompletableFuture versions of [V1Api.Tv]. */
    public inner class V1Tv internal constructor() {
        /**
         * `eventstv.php?d=` — TV listings for a day, optionally narrowed to a [sport], or to
         * a [country] **and** sport. The API returns an empty body when given a country
         * without a sport, so that combination is rejected here.
         */
        @JvmOverloads public fun day(date: LocalDate, sport: String? = null, country: String? = null): CompletableFuture<List<TvListing>> =
            call { client.v1.tv.day(date, sport, country) }

        /** `eventstv.php?c=` — upcoming listings on one channel, by name (e.g. `TSN 1`). */
        public fun channel(name: String): CompletableFuture<List<TvListing>> =
            call { client.v1.tv.channel(name) }

        /** `eventstv.php?id=` — upcoming listings on one channel, by [TvListing.channelId]. */
        public fun channel(channelId: Long): CompletableFuture<List<TvListing>> =
            call { client.v1.tv.channel(channelId) }
    }

    /** CompletableFuture versions of [V1Api.Video]. */
    public inner class V1Video internal constructor() {
        /**
         * `eventshighlights.php?d=` — events with highlight videos ([Event.video]) on a day,
         * optionally for one [leagueId] or [sport]. Free key: 2.
         */
        @JvmOverloads public fun highlights(date: LocalDate, leagueId: Long? = null, sport: String? = null): CompletableFuture<List<Event>> =
            call { client.v1.video.highlights(date, leagueId, sport) }
    }

    /** CompletableFuture versions of [V1Api.Live]. */
    public inner class V1Live internal constructor() {
        /** `livescore.php?s=` — live games for a sport, e.g. `Soccer`. */
        public fun sport(sport: String): CompletableFuture<List<LiveScore>> =
            call { client.v1.live.sport(sport) }
    }

    /** CompletableFuture versions of [V2Api]. */
    public inner class V2 internal constructor() {
        @get:JvmName("search") public val search: V2Search = V2Search()
        @get:JvmName("lookup") public val lookup: V2Lookup = V2Lookup()
        @get:JvmName("list") public val list: V2Lists = V2Lists()
        @get:JvmName("all") public val all: V2All = V2All()
        @get:JvmName("schedule") public val schedule: V2Schedule = V2Schedule()
        @get:JvmName("tv") public val tv: V2Tv = V2Tv()
        @get:JvmName("live") public val live: V2Live = V2Live()
    }

    /** CompletableFuture versions of [V2Api.Search]. */
    public inner class V2Search internal constructor() {
        public fun leagues(name: String): CompletableFuture<List<League>> =
            call { client.v2.search.leagues(name) }

        public fun teams(name: String): CompletableFuture<List<Team>> =
            call { client.v2.search.teams(name) }

        public fun players(name: String): CompletableFuture<List<Player>> =
            call { client.v2.search.players(name) }

        /**
         * Events by name. Needs the event's exact name as TheSportsDB writes it; a loose
         * `Arsenal vs Chelsea` finds nothing where v1 `searchevents.php` finds matches.
         */
        public fun events(name: String): CompletableFuture<List<Event>> =
            call { client.v2.search.events(name) }

        public fun venues(name: String): CompletableFuture<List<Venue>> =
            call { client.v2.search.venues(name) }
    }

    /** CompletableFuture versions of [V2Api.Lookup]. */
    public inner class V2Lookup internal constructor() {
        public fun league(id: Long): CompletableFuture<League?> =
            call { client.v2.lookup.league(id) }

        public fun team(id: Long): CompletableFuture<Team?> =
            call { client.v2.lookup.team(id) }

        public fun teamEquipment(teamId: Long): CompletableFuture<List<Equipment>> =
            call { client.v2.lookup.teamEquipment(teamId) }

        public fun player(id: Long): CompletableFuture<Player?> =
            call { client.v2.lookup.player(id) }

        public fun playerContracts(playerId: Long): CompletableFuture<List<Contract>> =
            call { client.v2.lookup.playerContracts(playerId) }

        public fun playerResults(playerId: Long): CompletableFuture<List<EventResult>> =
            call { client.v2.lookup.playerResults(playerId) }

        public fun playerHonours(playerId: Long): CompletableFuture<List<Honour>> =
            call { client.v2.lookup.playerHonours(playerId) }

        public fun playerMilestones(playerId: Long): CompletableFuture<List<Milestone>> =
            call { client.v2.lookup.playerMilestones(playerId) }

        /** A player's former teams (v1 calls these `formerteams`). */
        public fun playerTeams(playerId: Long): CompletableFuture<List<FormerTeam>> =
            call { client.v2.lookup.playerTeams(playerId) }

        public fun playerStats(playerId: Long): CompletableFuture<List<PlayerStat>> =
            call { client.v2.lookup.playerStats(playerId) }

        public fun event(id: Long): CompletableFuture<Event?> =
            call { client.v2.lookup.event(id) }

        public fun eventLineup(eventId: Long): CompletableFuture<List<LineupEntry>> =
            call { client.v2.lookup.eventLineup(eventId) }

        public fun eventResults(eventId: Long): CompletableFuture<List<EventResult>> =
            call { client.v2.lookup.eventResults(eventId) }

        public fun eventStats(eventId: Long): CompletableFuture<List<EventStat>> =
            call { client.v2.lookup.eventStats(eventId) }

        public fun eventTimeline(eventId: Long): CompletableFuture<List<TimelineEntry>> =
            call { client.v2.lookup.eventTimeline(eventId) }

        /** The channels showing an event. */
        public fun eventTv(eventId: Long): CompletableFuture<List<TvListing>> =
            call { client.v2.lookup.eventTv(eventId) }

        /** An event with its highlight video in [Event.video]. */
        public fun eventHighlights(eventId: Long): CompletableFuture<List<Event>> =
            call { client.v2.lookup.eventHighlights(eventId) }

        public fun venue(id: Long): CompletableFuture<Venue?> =
            call { client.v2.lookup.venue(id) }
    }

    /** CompletableFuture versions of [V2Api.Lists]. */
    public inner class V2Lists internal constructor() {
        /** A league's teams with badges and colours. No alternate names: look teams up by id for those. */
        public fun teams(leagueId: Long): CompletableFuture<List<Team>> =
            call { client.v2.list.teams(leagueId) }

        /** A league's seasons with badges, posters and descriptions. */
        public fun seasons(leagueId: Long): CompletableFuture<List<Season>> =
            call { client.v2.list.seasons(leagueId) }

        /**
         * A league's season posters and badges: every piece of season artwork, with who uploaded
         * it (several per season are possible). Listed in the official OpenAPI description; not on
         * the HTML documentation page.
         */
        public fun seasonPosters(leagueId: Long): CompletableFuture<List<SeasonPoster>> =
            call { client.v2.list.seasonPosters(leagueId) }

        /** A team's squad (summary fields). */
        public fun players(teamId: Long): CompletableFuture<List<Player>> =
            call { client.v2.list.players(teamId) }
    }

    /** CompletableFuture versions of [V2Api.All]. */
    public inner class V2All internal constructor() {
        public fun countries(): CompletableFuture<List<Country>> =
            call { client.v2.all.countries() }

        public fun sports(): CompletableFuture<List<Sport>> =
            call { client.v2.all.sports() }

        /** Every league (about 1,500): id, name, sport and alternate names only. */
        public fun leagues(): CompletableFuture<List<League>> =
            call { client.v2.all.leagues() }
    }

    /** CompletableFuture versions of [V2Api.Schedule]. */
    public inner class V2Schedule internal constructor() {
        public fun leagueNext(leagueId: Long): CompletableFuture<List<Event>> =
            call { client.v2.schedule.leagueNext(leagueId) }

        public fun leaguePrevious(leagueId: Long): CompletableFuture<List<Event>> =
            call { client.v2.schedule.leaguePrevious(leagueId) }

        public fun teamNext(teamId: Long): CompletableFuture<List<Event>> =
            call { client.v2.schedule.teamNext(teamId) }

        public fun teamPrevious(teamId: Long): CompletableFuture<List<Event>> =
            call { client.v2.schedule.teamPrevious(teamId) }

        public fun venueNext(venueId: Long): CompletableFuture<List<Event>> =
            call { client.v2.schedule.venueNext(venueId) }

        public fun venuePrevious(venueId: Long): CompletableFuture<List<Event>> =
            call { client.v2.schedule.venuePrevious(venueId) }

        /** A team's whole schedule, past and future, across all its competitions. */
        public fun teamFull(teamId: Long): CompletableFuture<List<Event>> =
            call { client.v2.schedule.teamFull(teamId) }

        /**
         * A league's whole season in one call (up to 3,000 events). Get the current season
         * name from [League.currentSeason].
         */
        public fun leagueSeason(leagueId: Long, season: String): CompletableFuture<List<Event>> =
            call { client.v2.schedule.leagueSeason(leagueId, season) }
    }

    /** CompletableFuture versions of [V2Api.Tv]. */
    public inner class V2Tv internal constructor() {
        /** Every listing worldwide on a day. */
        public fun day(date: LocalDate): CompletableFuture<List<TvListing>> =
            call { client.v2.tv.day(date) }

        /** About a week of listings for a country, e.g. `Canada`. */
        public fun country(country: String): CompletableFuture<List<TvListing>> =
            call { client.v2.tv.country(country) }

        /** Listings for a sport, e.g. `Ice Hockey`. */
        public fun sport(sport: String): CompletableFuture<List<TvListing>> =
            call { client.v2.tv.sport(sport) }

        /**
         * Listings for a channel by name. The name must use TheSportsDB's spelling
         * (`TSN 1`, not `TSN1`); partial names match too (`Sportsnet` finds `SportsNet West`).
         */
        public fun channel(name: String): CompletableFuture<List<TvListing>> =
            call { client.v2.tv.channel(name) }

        /** Listings for a channel by [TvListing.channelId]. */
        public fun channel(channelId: Long): CompletableFuture<List<TvListing>> =
            call { client.v2.tv.channel(channelId) }
    }

    /** CompletableFuture versions of [V2Api.Live]. */
    public inner class V2Live internal constructor() {
        /** Live games in a sport, e.g. `soccer`, `Ice Hockey`. */
        public fun sport(sport: String): CompletableFuture<List<LiveScore>> =
            call { client.v2.live.sport(sport) }

        /** Live games in one league. Empty when nothing is in play. */
        public fun league(leagueId: Long): CompletableFuture<List<LiveScore>> =
            call { client.v2.live.league(leagueId) }

        /** Every live game in every sport. */
        public fun all(): CompletableFuture<List<LiveScore>> =
            call { client.v2.live.all() }
    }

    /** CompletableFuture versions of [Helpers]. */
    public inner class HelpersFutures internal constructor() {
        /** A league's current season name, e.g. `2026-2027` or `2026`; null if the league is unknown. */
        public fun currentSeason(leagueId: Long): CompletableFuture<String?> =
            call { client.helpers.currentSeason(leagueId) }

        /**
         * Every event of a league's season ([season] defaults to the current one).
         * Premium: the whole season in one call. Free key: only the first 5 events.
         */
        @JvmOverloads public fun seasonEvents(leagueId: Long, season: String? = null): CompletableFuture<List<Event>> =
            call { client.helpers.seasonEvents(leagueId, season) }

        /**
         * Every event in one round (matchday) of a season ([season] defaults to the current one).
         * Premium: filtered from the season schedule. Free key: v1's undocumented `eventsround.php`,
         * which returns the whole round (premium keys get 404 from it, hence the two routes).
         */
        @JvmOverloads public fun roundEvents(leagueId: Long, round: Int, season: String? = null): CompletableFuture<List<Event>> =
            call { client.helpers.roundEvents(leagueId, round, season) }

        /**
         * A league's events starting in the next [days] UTC days, beginning with [from].
         * Premium: filtered from the season schedule (one or two calls). Free key: one
         * `eventsday` call per day, each limited to 3 events.
         */
        @JvmOverloads public fun upcomingLeagueEvents(leagueId: Long, days: Int = 7, from: LocalDate = LocalDate.now(ZoneOffset.UTC)): CompletableFuture<List<Event>> =
            call { client.helpers.upcomingLeagueEvents(leagueId, days, from) }

        /** A league's latest results. Premium: up to about 20. Free key: 1. */
        public fun recentLeagueResults(leagueId: Long): CompletableFuture<List<Event>> =
            call { client.helpers.recentLeagueResults(leagueId) }

        /**
         * A team's schedule across all competitions, past and future.
         * Premium: the full schedule (one call). Free key: the next and the last event only,
         * and only home games (a free-key limit).
         */
        public fun teamSchedule(teamId: Long): CompletableFuture<List<Event>> =
            call { client.helpers.teamSchedule(teamId) }

        /**
         * Events on a calendar day in your time zone. The API files events under their UTC date,
         * so a local day can span two API days; this fetches both and keeps the events that start
         * on [date] in [zone]. Optionally narrowed to a [sport] or a [leagueId].
         * Free key: at most 3 events per UTC day.
         */
        @JvmOverloads public fun eventsOnLocalDate(date: LocalDate, zone: ZoneId, sport: String? = null, leagueId: Long? = null): CompletableFuture<List<Event>> =
            call { client.helpers.eventsOnLocalDate(date, zone, sport, leagueId) }

        /**
         * Games in progress, optionally for one [sport] (e.g. `Soccer`) or one [leagueId].
         * Premium: v2 live scores. Free key: v1's undocumented live feed, which needs a sport;
         * for a league, the league's sport is looked up and the results filtered.
         *
         * Entries can be stale (a finished game may linger); check [LiveScore.updated].
         */
        @JvmOverloads public fun liveScores(sport: String? = null, leagueId: Long? = null): CompletableFuture<List<LiveScore>> =
            call { client.helpers.liveScores(sport, leagueId) }

        /**
         * A league's teams, with badges.
         * Premium: one call. Free key: the league's name is looked up, then up to 10 teams.
         */
        public fun leagueTeams(leagueId: Long): CompletableFuture<List<Team>> =
            call { client.helpers.leagueTeams(leagueId) }

        /** The channels showing an event. Free key: at most 2. */
        public fun eventChannels(eventId: Long): CompletableFuture<List<TvListing>> =
            call { client.helpers.eventChannels(eventId) }

        /**
         * A country's TV listings for the next [days] days from [from], optionally for one [sport].
         * Premium: about a week of the country's listings in one call, filtered here.
         * Free key: one call per day, which needs a [sport], and returns 1 listing per call.
         */
        @JvmOverloads public fun tvListings(country: String, sport: String? = null, days: Int = 7, from: LocalDate = LocalDate.now(ZoneOffset.UTC)): CompletableFuture<List<TvListing>> =
            call { client.helpers.tvListings(country, sport, days, from) }
    }
}
