# GENERATED by tools/unasync.py from src/thesportsdb_client/_async/_requester.py. Do not edit; edit the async source.
"""Builds URLs and runs every call through the rate limiter, retries, cache, de-duplication and parser.

GENERATED from ``_async/_requester.py`` by ``tools/unasync.py``. Do not edit.
"""

from __future__ import annotations

import threading
from collections import deque
from collections.abc import Callable, Mapping
from typing import TypeVar
from urllib.parse import quote

from .._envelope import Record, parse_records
from ..cache import Freshness
from ..config import Config
from ..errors import (
    HTTPStatusError,
    InvalidApiKeyError,
    NetworkError,
    PremiumRequiredError,
    RateLimitError,
)
from ..events import RequestEvent
from . import _compat
from ._transport import Transport, Response

T = TypeVar("T")


class RateLimiter:
    """Sliding window: at most ``permits`` calls in any ``window`` seconds. Callers wait for a slot."""

    def __init__(self, permits: int, window: float = 60.0) -> None:
        self._permits = permits
        self._window = window
        self._starts: deque[float] = deque()
        self._lock = _compat.Lock()

    def acquire(self) -> None:
        with self._lock:
            while True:
                t = _compat.now()
                while self._starts and t - self._starts[0] >= self._window:
                    self._starts.popleft()
                if len(self._starts) < self._permits:
                    self._starts.append(t)
                    return
                _compat.sleep(self._window - (t - self._starts[0]))


class _Trace:
    def __init__(self) -> None:
        self.status: int | None = None
        self.attempts = 0
        self.from_cache = False
        self.shared = False


class _Flight:
    def __init__(self) -> None:
        self.done = _compat.Event()
        self.finished = False  # False after done means the leader was cancelled
        self.body: str | None = None
        self.status: int | None = None
        self.error: Exception | None = None


class Requester:
    def __init__(self, config: Config, transport: Transport) -> None:
        self.config = config
        self.transport = transport
        rpm = config.effective_requests_per_minute
        self._limiter = RateLimiter(rpm) if rpm > 0 else None
        self._tier = "free" if config.is_free_key else "paid"
        self._flights: dict[str, _Flight] = {}
        self._flights_lock = threading.Lock()

    def v1(
        self,
        endpoint: str,
        record_key: str,
        freshness: Freshness,
        parse: Callable[[Record], T],
        **params: object,
    ) -> list[T]:
        """``GET /api/v1/json/{key}/{endpoint}?params``. None params are left out."""
        query = "&".join(f"{k}={quote(str(v), safe='')}" for k, v in params.items() if v is not None)
        suffix = f"{endpoint}?{query}" if query else endpoint
        base = self.config.base_url.rstrip("/") + "/api/v1/json/"
        url = base + quote(self.config.api_key, safe="") + "/" + suffix
        display = base + "***/" + suffix
        body = self._fetch(url, {}, display, f"v1:{self._tier}:{suffix}", freshness)
        return [parse(r) for r in parse_records(body, record_key, display)]

    def v2(self, record_key: str, freshness: Freshness, parse: Callable[[Record], T], *segments: object) -> list[T]:
        """``GET /api/v2/json/{segments...}`` with the key in the ``X-API-KEY`` header."""
        if self.config.is_free_key:
            raise PremiumRequiredError(
                "v2 endpoints need a premium key; free keys (123, 3) only work with v1 (client.v1)."
            )
        path = "/".join(quote(str(s), safe="") for s in segments)
        url = self.config.base_url.rstrip("/") + "/api/v2/json/" + path
        body = self._fetch(url, {"X-API-KEY": self.config.api_key}, url, f"v2:{path}", freshness)
        return [parse(r) for r in parse_records(body, record_key, url)]

    def _fetch(
        self, url: str, headers: Mapping[str, str], display: str, cache_key: str, freshness: Freshness
    ) -> str:
        started = _compat.now()
        trace = _Trace()
        error: BaseException | None = None
        try:
            cache = self.config.cache
            ttl = self.config.cache_policy.ttl(freshness)
            if cache is not None and ttl > 0:
                cached = cache.get(cache_key)
                if cached is not None:
                    trace.from_cache = True
                    return cached

            all_headers = {**headers, "User-Agent": self.config.user_agent}
            if self.config.deduplicate_requests:
                body = self._shared(cache_key, trace, lambda: self._send(url, all_headers, display, trace))
            else:
                body = self._send(url, all_headers, display, trace)

            # Don't cache an empty body: for v1 it can mean a transient problem, not "no results".
            if cache is not None and ttl > 0 and body.strip():
                cache.put(cache_key, body, ttl)
            return body
        except BaseException as e:
            error = e
            raise
        finally:
            self._notify(display, trace, _compat.now() - started, error)

    def _shared(self, key: str, trace: _Trace, block: Callable[[], str]) -> str:
        """Single flight: the first caller for ``key`` makes the request; identical calls that arrive
        meanwhile wait for its result. If that caller is cancelled, a waiter takes over."""
        while True:
            with self._flights_lock:
                flight = self._flights.get(key)
                leader = flight is None
                if flight is None:
                    flight = self._flights[key] = _Flight()
            if not leader:
                flight.done.wait()
                if not flight.finished:
                    continue
                trace.shared = True
                trace.status = flight.status
                if flight.error is not None:
                    raise flight.error
                assert flight.body is not None
                return flight.body
            try:
                body = block()
                flight.body, flight.status, flight.finished = body, trace.status, True
                return body
            except Exception as e:
                flight.error, flight.status, flight.finished = e, trace.status, True
                raise
            finally:
                with self._flights_lock:
                    self._flights.pop(key, None)
                flight.done.set()

    def _send(self, url: str, headers: Mapping[str, str], display: str, trace: _Trace) -> str:
        attempt = 0
        rate_limit_retried = False
        backoff = self.config.retry_backoff
        while True:
            if self._limiter is not None:
                self._limiter.acquire()
            trace.attempts += 1
            try:
                response: Response = self.transport.get(url, headers)
            except OSError as e:
                if attempt < self.config.max_retries:
                    attempt += 1
                    _compat.sleep(backoff)
                    backoff *= 2
                    continue
                raise NetworkError(f"Request to {display} failed: {e}") from e

            status = trace.status = response.status
            if 200 <= status < 300:
                return response.body
            if status == 429:
                wait = _seconds(response.header("Retry-After"))
                if self.config.retry_on_rate_limit and not rate_limit_retried:
                    rate_limit_retried = True
                    _compat.sleep(wait if wait is not None else self.config.rate_limit_wait)
                    continue
                raise RateLimitError(f"Rate limit exceeded calling {display}", wait)
            if 500 <= status < 600 and attempt < self.config.max_retries:
                attempt += 1
                _compat.sleep(backoff)
                backoff *= 2
                continue
            if "invalid premium api key" in response.body.lower():
                raise InvalidApiKeyError(
                    f"TheSportsDB rejected the API key (HTTP {status}, {display}). "
                    "Only the free keys (123, 3) and paid keys work; v2 needs a paid key."
                )
            raise HTTPStatusError(f"HTTP {status} from {display}", status, response.body[:300])

    def _notify(self, display: str, trace: _Trace, elapsed: float, error: BaseException | None) -> None:
        listener = self.config.request_listener
        if listener is None:
            return
        status = trace.status
        if status is None:
            if isinstance(error, HTTPStatusError):
                status = error.status
            elif isinstance(error, RateLimitError):
                status = 429
        try:
            listener(RequestEvent(display, status, trace.attempts, trace.from_cache, trace.shared, elapsed, error))
        except Exception:
            pass  # a failing listener must not break the call it is observing


def _seconds(value: str | None) -> float | None:
    try:
        return float(value.strip()) if value else None
    except ValueError:
        return None
