# GENERATED by tools/unasync.py from src/thesportsdb_client/_async/helpers.py. Do not edit; edit the async source.
"""Common tasks in one call. Each helper uses v2 with a premium key and v1 with a free key
(then the free keys' small limits apply). Any key other than the free keys that the API accepts
is a paid key, so no extra call is made to find out. Events come back sorted by start time.

GENERATED from ``_async/helpers.py`` by ``tools/unasync.py``. Do not edit.
"""

from __future__ import annotations

from collections.abc import Callable, Iterable
from datetime import date, datetime, time, timedelta, timezone, tzinfo
from typing import TYPE_CHECKING, TypeVar

from ..models import Event, LiveScore, Team, TvListing
from . import _compat

if TYPE_CHECKING:
    from .client import SportsDB

T = TypeVar("T")
_MAX = datetime.max.replace(tzinfo=timezone.utc)


class Helpers:
    def __init__(self, client: SportsDB) -> None:
        self._c = client

    @property
    def _premium(self) -> bool:
        return not self._c.config.is_free_key

    def current_season(self, league_id: int) -> str | None:
        """A league's current season name, e.g. ``2026-2027``; None if the league is unknown."""
        api = self._c.v2.lookup if self._premium else self._c.v1.lookup
        league = api.league(league_id)
        return league.current_season if league else None

    def season_events(self, league_id: int, season: str | None = None) -> list[Event]:
        """Every event of a season (default: current). Premium: one call. Free keys: the first 5 events."""
        name = season or self.current_season(league_id)
        if not name:
            return []
        if self._premium:
            events = self._c.v2.schedule.league_season(league_id, name)
        else:
            events = self._c.v1.schedule.season(league_id, name)
        return _by_start(events)

    def round_events(self, league_id: int, round: int, season: str | None = None) -> list[Event]:
        """One round (matchday). Premium: filtered from the season. Free keys: ``eventsround.php``
        (undocumented; the whole round). Premium keys get 404 from that endpoint, hence two routes."""
        if self._premium:
            return [e for e in self.season_events(league_id, season) if e.round == round]
        name = season or self.current_season(league_id)
        if not name:
            return []
        return _by_start(self._c.v1.schedule.round(league_id, round, name))

    def upcoming_league_events(self, league_id: int, days: int = 7, start: date | None = None) -> list[Event]:
        """Events in the next ``days`` UTC days from ``start`` (default: today, UTC).
        Premium: filtered from the season. Free keys: one ``eventsday.php`` call per day (3 a day)."""
        if not 1 <= days <= 31:
            raise ValueError("days must be between 1 and 31")
        first = start or datetime.now(timezone.utc).date()
        dates = [first + timedelta(days=n) for n in range(days)]
        if not self._premium:
            v1 = self._c.v1
            per_day = _compat.gather([_bind(v1.schedule.day, d, league_id) for d in dates])
            return _by_start(_distinct(e for day in per_day for e in day))
        wanted = set(dates)
        return [e for e in self.season_events(league_id) if e.date in wanted]

    def recent_league_results(self, league_id: int) -> list[Event]:
        """A league's latest results. Premium: about 20. Free keys: 1."""
        if self._premium:
            return _by_start(self._c.v2.schedule.league_previous(league_id))
        return _by_start(self._c.v1.schedule.league_past(league_id))

    def team_schedule(self, team_id: int) -> list[Event]:
        """A team's schedule, past and future. Premium: the full schedule. Free keys: next + last, home games only."""
        if self._premium:
            return _by_start(self._c.v2.schedule.team_full(team_id))
        last = self._c.v1.schedule.team_last(team_id)
        upcoming = self._c.v1.schedule.team_next(team_id)
        return _by_start(_distinct([*last, *upcoming]))

    def events_on_local_date(
        self, day: date, tz: tzinfo, sport: str | None = None, league_id: int | None = None
    ) -> list[Event]:
        """Events starting on ``day`` in time zone ``tz`` (e.g. ``ZoneInfo("America/Toronto")``).

        The API files events under their UTC date, so a local day can span two API days; this
        fetches each UTC day it overlaps and keeps the events that start on the local day.
        Free keys: at most 3 events per UTC day.
        """
        start = datetime.combine(day, time.min, tz).astimezone(timezone.utc)
        end = datetime.combine(day + timedelta(days=1), time.min, tz).astimezone(timezone.utc)
        utc_days = []
        d = start.date()
        while datetime.combine(d, time.min, timezone.utc) < end:
            utc_days.append(d)
            d += timedelta(days=1)
        v1 = self._c.v1
        per_day = _compat.gather([_bind(v1.schedule.day, d, league_id, sport) for d in utc_days])
        events = _distinct(e for chunk in per_day for e in chunk)
        return _by_start([e for e in events if (start <= e.timestamp < end if e.timestamp else e.date == day)])

    def live_scores(self, sport: str | None = None, league_id: int | None = None) -> list[LiveScore]:
        """Games in progress. Premium: v2. Free keys: v1's undocumented feed, which needs a sport; for a
        league, its sport is looked up and the feed filtered. Entries can be stale: check ``updated``."""
        if self._premium:
            if league_id is not None:
                return self._c.v2.live.league(league_id)
            if sport is not None:
                return self._c.v2.live.sport(sport)
            return self._c.v2.live.all()
        if sport is None and league_id is not None:
            league = self._c.v1.lookup.league(league_id)
            sport = league.sport if league else None
        if sport is None:
            raise ValueError("With a free key, live scores need a sport or a league_id")
        scores = self._c.v1.live.sport(sport)
        return [s for s in scores if league_id is None or s.league_id == league_id]

    def league_teams(self, league_id: int) -> list[Team]:
        """A league's teams with badges. Free keys: looks up the league name, then up to 10 teams."""
        if self._premium:
            return self._c.v2.list.teams(league_id)
        league = self._c.v1.lookup.league(league_id)
        if league is None or league.name is None:
            return []
        return self._c.v1.list.teams_in_league(league.name)

    def event_channels(self, event_id: int) -> list[TvListing]:
        """The channels showing an event. Free keys: at most 2."""
        if self._premium:
            return self._c.v2.lookup.event_tv(event_id)
        return self._c.v1.lookup.event_tv(event_id)

    def tv_listings(
        self, country: str, sport: str | None = None, days: int = 7, start: date | None = None
    ) -> list[TvListing]:
        """A country's TV listings for ``days`` days. Premium: the country's week in one call, filtered.
        Free keys: one call per day, which needs a sport."""
        if not 1 <= days <= 31:
            raise ValueError("days must be between 1 and 31")
        first = start or datetime.now(timezone.utc).date()
        dates = [first + timedelta(days=n) for n in range(days)]
        if self._premium:
            wanted = set(dates)
            listings = [
                t for t in self._c.v2.tv.country(country)
                if t.date in wanted and (sport is None or (t.sport or "").lower() == sport.lower())
            ]
        else:
            if sport is None:
                raise ValueError("With a free key, TV listings for a country need a sport")
            tv = self._c.v1.tv
            per_day = _compat.gather([_bind_tv(tv.day, d, sport, country) for d in dates])
            listings = [t for chunk in per_day for t in chunk]
        return sorted(listings, key=lambda t: t.timestamp or _MAX)


def _bind(day: Callable[..., list[Event]], d: date, league_id: int | None, sport: str | None = None
          ) -> Callable[[], list[Event]]:
    return lambda: day(d, sport=sport, league_id=league_id)


def _bind_tv(day: Callable[..., list[TvListing]], d: date, sport: str, country: str
             ) -> Callable[[], list[TvListing]]:
    return lambda: day(d, sport=sport, country=country)


def _by_start(events: list[Event]) -> list[Event]:
    return sorted(events, key=lambda e: e.timestamp or _MAX)


def _distinct(events: Iterable[Event]) -> list[Event]:
    seen: set[object] = set()
    out = []
    for e in events:
        key: object = e.id if e.id is not None else e
        if key not in seen:
            seen.add(key)
            out.append(e)
    return out
