#!/usr/bin/env python3
"""Generates src/main/kotlin/sportsdb/SportsDbFutures.kt (the Java-friendly CompletableFuture
facade) from the public suspend functions in V1Api.kt and V2Api.kt. Run after changing either."""
import re, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
src = root / "src/main/kotlin/sportsdb"

def parse(path):
    text = (src / path).read_text()
    groups = {}
    # Each nested class: "public class Search internal constructor(private val r: Requester) {"
    for cm in re.finditer(r"public class (\w+) internal constructor\(private val r: Requester\) \{", text):
        cls = cm.group(1)
        start = cm.end(); depth = 1; i = start
        while depth:
            depth += {"{": 1, "}": -1}.get(text[i], 0); i += 1
        body = text[start:i]
        funs = []
        for fm in re.finditer(r"((?:[ \t]*/\*\*.*?\*/\s*)?)public suspend fun (\w+)\((.*?)\): ([\w<>?, ]+?)\s*[={]", body, re.S):
            doc, name, params, ret = fm.groups()
            params = " ".join(params.split()).rstrip(",")
            funs.append((doc.strip(), name, params, ret.strip()))
        groups[cls] = funs
    # property name for each class: "public val search: Search = Search(r)"
    props = dict((c, p) for p, c in re.findall(r"public val (\w+): (\w+) = \2\(r\)", text))
    return groups, props

def arg_names(params):
    if not params: return ""
    names = []
    depth = 0; cur = ""
    for ch in params:
        if ch in "<(": depth += 1
        if ch in ">)": depth -= 1
        if ch == "," and depth == 0: names.append(cur); cur = ""
        else: cur += ch
    names.append(cur)
    return ", ".join(n.split(":")[0].strip() for n in names if n.strip())

def emit(version, path):
    groups, props = parse(path)
    out = [f"    /** CompletableFuture versions of [{version.upper()}Api]. */",
           f"    public inner class {version.upper()} internal constructor() {{"]
    for cls, funs in groups.items():
        prop = props[cls]
        out.append(f"        @get:JvmName(\"{prop}\") public val {prop}: {version.upper()}{cls} = {version.upper()}{cls}()")
    out.append("    }\n")
    for cls, funs in groups.items():
        prop = props[cls]
        out.append(f"    /** CompletableFuture versions of [{version.upper()}Api.{cls}]. */")
        out.append(f"    public inner class {version.upper()}{cls} internal constructor() {{")
        for doc, name, params, ret in funs:
            ann = "@JvmOverloads " if "=" in params else ""
            if doc:
                lines = [l.strip() for l in doc.splitlines()]
                out.append("        " + lines[0])
                out.extend("         " + l for l in lines[1:])
            out.append(f"        {ann}public fun {name}({params}): CompletableFuture<{ret}> =")
            out.append(f"            call {{ client.{version}.{prop}.{name}({arg_names(params)}) }}")
            out.append("")
        out[-1] = "    }\n"
    return "\n".join(out)

header = '''// GENERATED by tools/gen-futures.py from V1Api.kt and V2Api.kt. Do not edit by hand.
package sportsdb

import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.future.future
import sportsdb.model.*
import java.time.LocalDate
import java.util.concurrent.CompletableFuture

/**
 * A Java-friendly wrapper: every [SportsDbClient] method, returning a [CompletableFuture].
 *
 * ```java
 * SportsDbConfig config = new SportsDbConfig();
 * config.setApiKey(System.getenv("THESPORTSDB_API_KEY"));
 * try (SportsDbFutures db = new SportsDbFutures(config)) {
 *     Team team = db.v1().lookup().team(133604).join();
 *     db.v2().schedule().leagueNext(4328).thenAccept(events -> ...);
 * }
 * ```
 *
 * Single lookups complete with `null` when nothing is found. Failures complete the future
 * exceptionally with a [SportsDbException] (wrapped in `CompletionException` by `join()`).
 * [close] cancels calls still running.
 */
public class SportsDbFutures(
    /** The underlying client, for Kotlin callers or for sharing its cache and rate limiter. */
    public val client: SportsDbClient,
    private val scope: CoroutineScope,
) : AutoCloseable {
    public constructor(client: SportsDbClient) : this(client, CoroutineScope(SupervisorJob() + Dispatchers.IO))
    public constructor(config: SportsDbConfig) : this(SportsDbClient(config))
    public constructor() : this(SportsDbConfig())

    @get:JvmName("v1") public val v1: V1 = V1()
    @get:JvmName("v2") public val v2: V2 = V2()

    /** See [SportsDbClient.isPremiumKey]. */
    public fun isPremiumKey(): CompletableFuture<Boolean> = scope.future { client.isPremiumKey() }

    override fun close(): Unit = scope.cancel()

    private fun <T> call(block: suspend () -> T): CompletableFuture<T> = scope.future { block() }

'''
(src / "SportsDbFutures.kt").write_text(header + emit("v1", "V1Api.kt") + "\n" + emit("v2", "V2Api.kt") + "}\n")
print("wrote", src / "SportsDbFutures.kt")
