<?php

// GENERATED by php/tools/gen_models.py from the Kotlin model Contract. Do not edit.

declare(strict_types=1);

namespace RohanG27\TheSportsDb\Model;

use RohanG27\TheSportsDb\Internal\Rec;

/**
 * A player's contract (`lookupcontracts.php`, `lookup/player_contracts`).
 */
final readonly class Contract extends ApiRecord
{
    /** `id` */
    public ?int $id;
    /** `idPlayer` */
    public ?int $playerId;
    /** `strPlayer` */
    public ?string $player;
    /** `idTeam` */
    public ?int $teamId;
    /** `strTeam` */
    public ?string $team;
    /** `strBadge` */
    public ?string $badge;
    /** `strYearStart` */
    public ?int $yearStart;
    /** `strYearEnd` */
    public ?int $yearEnd;
    /** `strWage`, as text */
    public ?string $wage;
    /** `strSport` */
    public ?string $sport;

    /**
     * @internal Records are built by the client from API responses.
     * @param array<string, string|null> $raw
     */
    public function __construct(array $raw)
    {
        parent::__construct($raw);
        $r = new Rec($raw);
        $this->id = $r->id('id');
        $this->playerId = $r->id('idPlayer');
        $this->player = $r->s('strPlayer');
        $this->teamId = $r->id('idTeam');
        $this->team = $r->s('strTeam');
        $this->badge = $r->s('strBadge');
        $this->yearStart = $r->year('strYearStart');
        $this->yearEnd = $r->year('strYearEnd');
        $this->wage = $r->s('strWage');
        $this->sport = $r->s('strSport');
    }

    public function __toString(): string
    {
        return "Contract(player={$this->fmt($this->player)}, team={$this->fmt($this->team)}, yearStart={$this->fmt($this->yearStart)}, yearEnd={$this->fmt($this->yearEnd)})";
    }
}
