<?php

// GENERATED by php/tools/gen_models.py from the Kotlin model Country. Do not edit.

declare(strict_types=1);

namespace RohanG27\TheSportsDb\Model;

use RohanG27\TheSportsDb\Internal\Rec;

/**
 * A country (`all_countries.php`, `all/countries`). v1 returns only [name] and [flag32].
 */
final readonly class Country extends ApiRecord
{
    /** `name_en`. Use this name for country filters. */
    public ?string $name;
    /** `name_fr` (v2) */
    public ?string $nameFr;
    /** `code` (v2), a two-letter code */
    public ?string $code;
    /** `flag_url_16` (v2) */
    public ?string $flag16;
    /** `flag_url_32` */
    public ?string $flag32;
    /** `flag_url_64` (v2) */
    public ?string $flag64;
    /** `idAPIfootball` (v2) */
    public ?int $apiFootballId;

    /**
     * @internal Records are built by the client from API responses.
     * @param array<string, string|null> $raw
     */
    public function __construct(array $raw)
    {
        parent::__construct($raw);
        $r = new Rec($raw);
        $this->name = $r->s('name_en');
        $this->nameFr = $r->s('name_fr');
        $this->code = $r->s('code');
        $this->flag16 = $r->s('flag_url_16');
        $this->flag32 = $r->s('flag_url_32');
        $this->flag64 = $r->s('flag_url_64');
        $this->apiFootballId = $r->id('idAPIfootball');
    }

    public function __toString(): string
    {
        return "Country(name={$this->fmt($this->name)}, code={$this->fmt($this->code)})";
    }
}
