<?php

// GENERATED by php/tools/gen_models.py from the Kotlin model Equipment. Do not edit.

declare(strict_types=1);

namespace SportsDb\Model;

use SportsDb\Internal\Rec;

/**
 * A team kit (`lookupequipment.php`, `lookup/team_equipment`).
 */
final readonly class Equipment extends ApiRecord
{
    /** `idEquipment` */
    public ?int $id;
    /** `idTeam` */
    public ?int $teamId;
    /** `strSeason` */
    public ?string $season;
    /** `strType`, e.g. `1st`, `2nd`, `GK` */
    public ?string $type;
    /** `strEquipment`: the image */
    public ?string $image;
    /** `strUsername`: who uploaded it */
    public ?string $uploadedBy;
    /** `date`: when it was added (zone not stated) (zone not stated) */
    public ?\DateTimeImmutable $added;

    /**
     * @internal Records are built by the client from API responses.
     * @param array<string, string|null> $raw
     */
    public function __construct(array $raw)
    {
        parent::__construct($raw);
        $r = new Rec($raw);
        $this->id = $r->id('idEquipment');
        $this->teamId = $r->id('idTeam');
        $this->season = $r->s('strSeason');
        $this->type = $r->s('strType');
        $this->image = $r->s('strEquipment');
        $this->uploadedBy = $r->s('strUsername');
        $this->added = $r->localDateTime('date');
    }

    public function __toString(): string
    {
        return "Equipment(teamId={$this->fmt($this->teamId)}, season={$this->fmt($this->season)}, type={$this->fmt($this->type)})";
    }
}
