<?php

// GENERATED by php/tools/gen_models.py from the Kotlin model EventStat. Do not edit.

declare(strict_types=1);

namespace RohanG27\TheSportsDb\Model;

use RohanG27\TheSportsDb\Internal\Rec;

/**
 * One team statistic for an event, home vs away (`lookupeventstats.php`, `lookup/event_stats`).
 */
final readonly class EventStat extends ApiRecord
{
    /** `idStatistic` */
    public ?int $id;
    /** `idEvent` */
    public ?int $eventId;
    /** `strEvent` */
    public ?string $event;
    /** `strStat`, e.g. `Shots on Goal`, `Ball Possession` */
    public ?string $name;
    /** `intHome` */
    public ?float $home;
    /** `intAway` */
    public ?float $away;
    /** `idApiFootball` (note the different capitalisation in the API) */
    public ?int $apiFootballId;

    /**
     * @internal Records are built by the client from API responses.
     * @param array<string, string|null> $raw
     */
    public function __construct(array $raw)
    {
        parent::__construct($raw);
        $r = new Rec($raw);
        $this->id = $r->id('idStatistic');
        $this->eventId = $r->id('idEvent');
        $this->event = $r->s('strEvent');
        $this->name = $r->s('strStat');
        $this->home = $r->float('intHome');
        $this->away = $r->float('intAway');
        $this->apiFootballId = $r->id('idApiFootball');
    }

    public function __toString(): string
    {
        return "EventStat(eventId={$this->fmt($this->eventId)}, name={$this->fmt($this->name)}, home={$this->fmt($this->home)}, away={$this->fmt($this->away)})";
    }
}
