<?php

// GENERATED by php/tools/gen_models.py from the Kotlin model EventResult. Do not edit.

declare(strict_types=1);

namespace RohanG27\TheSportsDb\Model;

use RohanG27\TheSportsDb\Internal\Rec;

/**
 * One competitor's result in an individual-sport event: a race, a golf tournament, a
 * fight. Returned both per player (`playerresults.php`) and per event (`eventresults.php`).
 */
final readonly class EventResult extends ApiRecord
{
    /** `idResult` */
    public ?int $id;
    /** `idEvent` */
    public ?int $eventId;
    /** `strEvent` */
    public ?string $event;
    /** `dateEvent` (a date, as midnight UTC) */
    public ?\DateTimeImmutable $date;
    /** `strSeason` */
    public ?string $season;
    /** `strSport` */
    public ?string $sport;
    /** `strCountry` */
    public ?string $country;
    /** `idPlayer` */
    public ?int $playerId;
    /** `strPlayer` */
    public ?string $player;
    /** `idTeam` */
    public ?int $teamId;
    /** `intPosition`: finishing position */
    public ?int $position;
    /** `intPoints` */
    public ?int $points;
    /** `strResult`: free text */
    public ?string $result;
    /** `strDetail`: e.g. a time gap `+29.520` */
    public ?string $detail;

    /**
     * @internal Records are built by the client from API responses.
     * @param array<string, string|null> $raw
     */
    public function __construct(array $raw)
    {
        parent::__construct($raw);
        $r = new Rec($raw);
        $this->id = $r->id('idResult');
        $this->eventId = $r->id('idEvent');
        $this->event = $r->s('strEvent');
        $this->date = $r->date('dateEvent');
        $this->season = $r->s('strSeason');
        $this->sport = $r->s('strSport');
        $this->country = $r->s('strCountry');
        $this->playerId = $r->id('idPlayer');
        $this->player = $r->s('strPlayer');
        $this->teamId = $r->id('idTeam');
        $this->position = $r->int('intPosition');
        $this->points = $r->int('intPoints');
        $this->result = $r->s('strResult');
        $this->detail = $r->s('strDetail');
    }

    public function __toString(): string
    {
        return "EventResult(eventId={$this->fmt($this->eventId)}, player={$this->fmt($this->player)}, position={$this->fmt($this->position)})";
    }
}
