<?php

// GENERATED by php/tools/gen_models.py from the Kotlin model Event. Do not edit.

declare(strict_types=1);

namespace SportsDb\Model;

use SportsDb\Internal\Rec;

/**
 * A game, match, race or other event. Also used for video highlights.
 *
 * Schedules and lists fill fewer fields than a lookup by id: v1 `eventsseason.php` and v2
 * `schedule/...` leave out descriptions, officials, spectators and the like.
 *
 * Times:** [timestamp], [date] and [time] are UTC. [localDate] and [localTime] are the
 * venue's local time and are often missing for future events.
 */
final readonly class Event extends ApiRecord
{
    /** `idEvent` */
    public ?int $id;
    /** `strEvent`, e.g. `Arsenal vs Chelsea` */
    public ?string $name;
    /** `strEventAlternate`, e.g. `Chelsea @ Arsenal` */
    public ?string $alternateName;
    /** `strFilename`: `{league} {date} {home} vs {away}`, searchable with `searchfilename.php` */
    public ?string $filename;
    /** `strSport` */
    public ?string $sport;
    /** `idLeague` */
    public ?int $leagueId;
    /** `strLeague` */
    public ?string $league;
    /** `strLeagueBadge` */
    public ?string $leagueBadge;
    /** `strSeason` */
    public ?string $season;
    /** `intRound`: matchday or round number */
    public ?int $round;
    /** `strGroup`: a cup group or conference */
    public ?string $group;
    /** `idHomeTeam` */
    public ?int $homeTeamId;
    /** `strHomeTeam` */
    public ?string $homeTeam;
    /** `strHomeTeamBadge` */
    public ?string $homeTeamBadge;
    /** `idAwayTeam` */
    public ?int $awayTeamId;
    /** `strAwayTeam` */
    public ?string $awayTeam;
    /** `strAwayTeamBadge` */
    public ?string $awayTeamBadge;
    /** `intHomeScore`: null until the event has a score */
    public ?int $homeScore;
    /** `intAwayScore` */
    public ?int $awayScore;
    /** `intHomeScoreExtra`: extra time or shoot-out */
    public ?int $homeScoreExtra;
    /** `intAwayScoreExtra` */
    public ?int $awayScoreExtra;
    /** `strTimestamp`: the start time (UTC) (UTC) */
    public ?\DateTimeImmutable $timestamp;
    /** `dateEvent` (UTC) (a date, as midnight UTC) */
    public ?\DateTimeImmutable $date;
    /** `strTime` (UTC) (HH:MM:SS) */
    public ?string $time;
    /** `dateEventLocal`: the venue's local date (a date, as midnight UTC) */
    public ?\DateTimeImmutable $localDate;
    /** `strTimeLocal`: the venue's local time (HH:MM:SS) */
    public ?string $localTime;
    /** `strStatus`: the raw code (`NS`, `2H`, `FT`, `Q3`, `PST`...); see [status] */
    public ?string $statusCode;
    /** `strPostponed` */
    public ?bool $isPostponed;
    /** `idVenue` */
    public ?int $venueId;
    /** `strVenue` */
    public ?string $venue;
    /** `strCity` */
    public ?string $city;
    /** `strCountry` */
    public ?string $country;
    /** `intSpectators` */
    public ?int $spectators;
    /** `strOfficial`: the referee */
    public ?string $official;
    /** `strResult`: free-text result, sometimes with HTML `<br>` */
    public ?string $resultText;
    /** `strDescriptionEN` */
    public ?string $description;
    /** `strThumb` */
    public ?string $thumb;
    /** `strPoster` */
    public ?string $poster;
    /** `strBanner` */
    public ?string $banner;
    /** `strSquare` */
    public ?string $square;
    /** `strFanart` */
    public ?string $fanart;
    /** `strMap` */
    public ?string $map;
    /** `strVideo`: a highlights video, usually YouTube */
    public ?string $video;
    /** `strTweet1` */
    public ?string $tweet;
    /** `strWeather` */
    public ?string $weather;
    /** `intScore`: the users' rating of the event */
    public ?float $rating;
    /** `intScoreVotes` */
    public ?int $ratingVotes;
    /** `strLocked` */
    public ?bool $isLocked;
    /** `idAPIfootball` */
    public ?int $apiFootballId;

    /**
     * @internal Records are built by the client from API responses.
     * @param array<string, string|null> $raw
     */
    public function __construct(array $raw)
    {
        parent::__construct($raw);
        $r = new Rec($raw);
        $this->id = $r->id('idEvent');
        $this->name = $r->s('strEvent');
        $this->alternateName = $r->s('strEventAlternate');
        $this->filename = $r->s('strFilename');
        $this->sport = $r->s('strSport');
        $this->leagueId = $r->id('idLeague');
        $this->league = $r->s('strLeague');
        $this->leagueBadge = $r->s('strLeagueBadge');
        $this->season = $r->s('strSeason');
        $this->round = $r->int('intRound');
        $this->group = $r->s('strGroup');
        $this->homeTeamId = $r->id('idHomeTeam');
        $this->homeTeam = $r->s('strHomeTeam');
        $this->homeTeamBadge = $r->s('strHomeTeamBadge');
        $this->awayTeamId = $r->id('idAwayTeam');
        $this->awayTeam = $r->s('strAwayTeam');
        $this->awayTeamBadge = $r->s('strAwayTeamBadge');
        $this->homeScore = $r->int('intHomeScore');
        $this->awayScore = $r->int('intAwayScore');
        $this->homeScoreExtra = $r->int('intHomeScoreExtra');
        $this->awayScoreExtra = $r->int('intAwayScoreExtra');
        $this->timestamp = $r->instant('strTimestamp');
        $this->date = $r->date('dateEvent');
        $this->time = $r->time('strTime');
        $this->localDate = $r->date('dateEventLocal');
        $this->localTime = $r->time('strTimeLocal');
        $this->statusCode = $r->s('strStatus');
        $this->isPostponed = $r->bool('strPostponed');
        $this->venueId = $r->id('idVenue');
        $this->venue = $r->s('strVenue');
        $this->city = $r->s('strCity');
        $this->country = $r->s('strCountry');
        $this->spectators = $r->int('intSpectators');
        $this->official = $r->s('strOfficial');
        $this->resultText = $r->s('strResult');
        $this->description = $r->s('strDescriptionEN');
        $this->thumb = $r->s('strThumb');
        $this->poster = $r->s('strPoster');
        $this->banner = $r->s('strBanner');
        $this->square = $r->s('strSquare');
        $this->fanart = $r->s('strFanart');
        $this->map = $r->s('strMap');
        $this->video = $r->s('strVideo');
        $this->tweet = $r->s('strTweet1');
        $this->weather = $r->s('strWeather');
        $this->rating = $r->float('intScore');
        $this->ratingVotes = $r->int('intScoreVotes');
        $this->isLocked = $r->locked();
        $this->apiFootballId = $r->id('idAPIfootball');
    }

    public function __toString(): string
    {
        return "Event(id={$this->fmt($this->id)}, name={$this->fmt($this->name)}, timestamp={$this->fmt($this->timestamp)}, statusCode={$this->fmt($this->statusCode)})";
    }

    /** The status code read as a broad status. */
    public function status(): EventStatus
    {
        return EventStatus::of($this->statusCode);
    }
}
