<?php

// GENERATED by php/tools/gen_models.py from the Kotlin model FormerTeam. Do not edit.

declare(strict_types=1);

namespace RohanG27\TheSportsDb\Model;

use RohanG27\TheSportsDb\Internal\Rec;

/**
 * A team a player used to play for (`lookupformerteams.php`, `lookup/player_teams`).
 */
final readonly class FormerTeam extends ApiRecord
{
    /** `id` */
    public ?int $id;
    /** `idPlayer` */
    public ?int $playerId;
    /** `strPlayer` */
    public ?string $player;
    /** `idFormerTeam`: the team's `idTeam` */
    public ?int $teamId;
    /** `strFormerTeam` */
    public ?string $team;
    /** `strBadge` */
    public ?string $badge;
    /** `strJoined`: usually a year, as text */
    public ?string $joined;
    /** `strDeparted`: usually a year, as text */
    public ?string $departed;
    /** `strMoveType`, e.g. `Permanent`, `Loan` */
    public ?string $moveType;
    /** `intAppearances` */
    public ?int $appearances;
    /** `intGoals` */
    public ?int $goals;
    /** `strSport` */
    public ?string $sport;

    /**
     * @internal Records are built by the client from API responses.
     * @param array<string, string|null> $raw
     */
    public function __construct(array $raw)
    {
        parent::__construct($raw);
        $r = new Rec($raw);
        $this->id = $r->id('id');
        $this->playerId = $r->id('idPlayer');
        $this->player = $r->s('strPlayer');
        $this->teamId = $r->id('idFormerTeam');
        $this->team = $r->s('strFormerTeam');
        $this->badge = $r->s('strBadge');
        $this->joined = $r->s('strJoined');
        $this->departed = $r->s('strDeparted');
        $this->moveType = $r->s('strMoveType');
        $this->appearances = $r->int('intAppearances');
        $this->goals = $r->int('intGoals');
        $this->sport = $r->s('strSport');
    }

    public function __toString(): string
    {
        return "FormerTeam(player={$this->fmt($this->player)}, team={$this->fmt($this->team)}, joined={$this->fmt($this->joined)}, departed={$this->fmt($this->departed)})";
    }
}
