<?php

// GENERATED by php/tools/gen_models.py from the Kotlin model Honour. Do not edit.

declare(strict_types=1);

namespace RohanG27\TheSportsDb\Model;

use RohanG27\TheSportsDb\Internal\Rec;

/**
 * A trophy a player won (`lookuphonours.php`, `lookup/player_honours`).
 */
final readonly class Honour extends ApiRecord
{
    /** `id`: this record */
    public ?int $id;
    /** `idHonour`: the honour itself, shared by everyone who won it */
    public ?int $honourId;
    /** `strHonour`, e.g. `Copa Libertadores` */
    public ?string $name;
    /** `strSeason` */
    public ?string $season;
    /** `idPlayer` */
    public ?int $playerId;
    /** `strPlayer` */
    public ?string $player;
    /** `idTeam` */
    public ?int $teamId;
    /** `strTeam` */
    public ?string $team;
    /** `strTeamBadge` */
    public ?string $teamBadge;
    /** `idLeague` */
    public ?int $leagueId;
    /** `strSport` */
    public ?string $sport;
    /** `strHonourLogo` */
    public ?string $logo;
    /** `strHonourTrophy` */
    public ?string $trophy;

    /**
     * @internal Records are built by the client from API responses.
     * @param array<string, string|null> $raw
     */
    public function __construct(array $raw)
    {
        parent::__construct($raw);
        $r = new Rec($raw);
        $this->id = $r->id('id');
        $this->honourId = $r->id('idHonour');
        $this->name = $r->s('strHonour');
        $this->season = $r->s('strSeason');
        $this->playerId = $r->id('idPlayer');
        $this->player = $r->s('strPlayer');
        $this->teamId = $r->id('idTeam');
        $this->team = $r->s('strTeam');
        $this->teamBadge = $r->s('strTeamBadge');
        $this->leagueId = $r->id('idLeague');
        $this->sport = $r->s('strSport');
        $this->logo = $r->s('strHonourLogo');
        $this->trophy = $r->s('strHonourTrophy');
    }

    public function __toString(): string
    {
        return "Honour(player={$this->fmt($this->player)}, name={$this->fmt($this->name)}, season={$this->fmt($this->season)})";
    }
}
