<?php

// GENERATED by php/tools/gen_models.py from the Kotlin model League. Do not edit.

declare(strict_types=1);

namespace RohanG27\TheSportsDb\Model;

use RohanG27\TheSportsDb\Internal\Rec;

/**
 * A league or cup. Lists (`all_leagues.php`, v2 `search/league`) fill only a few fields;
 * look it up by id for the rest.
 */
final readonly class League extends ApiRecord
{
    /** `idLeague` */
    public ?int $id;
    /** `strLeague` */
    public ?string $name;
    /** @var list<string> `strLeagueAlternate`, split on commas */
    public array $alternateNames;
    /** `strSport` */
    public ?string $sport;
    /** `strCountry` */
    public ?string $country;
    /** `strGender` */
    public ?string $gender;
    /** `strCurrentSeason`, e.g. `2026-2027` or `2026`. Pass it to season endpoints. */
    public ?string $currentSeason;
    /** `intDivision`: 1 for a top flight; cups often use 0 or 99 */
    public ?int $division;
    /** `idCup`: true for a cup competition */
    public ?bool $isCup;
    /** `intFormedYear` */
    public ?int $formedYear;
    /** `dateFirstEvent` (a date, as midnight UTC) */
    public ?\DateTimeImmutable $firstEventDate;
    /** `strComplete`: whether TheSportsDB considers its data complete */
    public ?bool $isComplete;
    /** `strNaming`: the event-name template, e.g. `{strHomeTeam} vs {strAwayTeam}` */
    public ?string $eventNaming;
    /** `strTvRights`: free text */
    public ?string $tvRights;
    /** `strBadge` */
    public ?string $badge;
    /** `strLogo` */
    public ?string $logo;
    /** `strBanner` */
    public ?string $banner;
    /** `strPoster` */
    public ?string $poster;
    /** `strTrophy` */
    public ?string $trophy;
    /** @var list<string> `strFanart1`..`strFanart4` */
    public array $fanart;
    /** @var array<string, string> `strDescriptionEN`, `strDescriptionDE`, ... keyed by language code (`EN`, `DE`) */
    public array $descriptions;
    public Socials $socials;
    /** `strLocked` */
    public ?bool $isLocked;
    /** `idAPIfootball` */
    public ?int $apiFootballId;
    /** `idAPIfootballv3` */
    public ?int $apiFootballV3Id;

    /**
     * @internal Records are built by the client from API responses.
     * @param array<string, string|null> $raw
     */
    public function __construct(array $raw)
    {
        parent::__construct($raw);
        $r = new Rec($raw);
        $this->id = $r->id('idLeague');
        $this->name = $r->s('strLeague');
        $this->alternateNames = $r->csv('strLeagueAlternate');
        $this->sport = $r->s('strSport');
        $this->country = $r->s('strCountry');
        $this->gender = $r->s('strGender');
        $this->currentSeason = $r->s('strCurrentSeason');
        $this->division = $r->int('intDivision');
        $this->isCup = $r->bool('idCup');
        $this->formedYear = $r->year('intFormedYear');
        $this->firstEventDate = $r->date('dateFirstEvent');
        $this->isComplete = $r->bool('strComplete');
        $this->eventNaming = $r->s('strNaming');
        $this->tvRights = $r->s('strTvRights');
        $this->badge = $r->s('strBadge');
        $this->logo = $r->s('strLogo');
        $this->banner = $r->s('strBanner');
        $this->poster = $r->s('strPoster');
        $this->trophy = $r->s('strTrophy');
        $this->fanart = $r->numbered('strFanart', 4);
        $this->descriptions = $r->descriptions();
        $this->socials = Socials::fromRec($r);
        $this->isLocked = $r->locked();
        $this->apiFootballId = $r->id('idAPIfootball');
        $this->apiFootballV3Id = $r->id('idAPIfootballv3');
    }

    public function __toString(): string
    {
        return "League(id={$this->fmt($this->id)}, name={$this->fmt($this->name)})";
    }

    /** The English description. */
    public function description(): ?string
    {
        return $this->descriptions['EN'] ?? null;
    }
}
