<?php

// GENERATED by php/tools/gen_models.py from the Kotlin model LineupEntry. Do not edit.

declare(strict_types=1);

namespace SportsDb\Model;

use SportsDb\Internal\Rec;

/**
 * One player in an event's lineup (`lookuplineup.php`, `lookup/event_lineup`).
 */
final readonly class LineupEntry extends ApiRecord
{
    /** `idLineup` */
    public ?int $id;
    /** `idEvent` */
    public ?int $eventId;
    /** `strEvent` (v2) */
    public ?string $event;
    /** `idPlayer` */
    public ?int $playerId;
    /** `strPlayer` */
    public ?string $player;
    /** `idTeam` */
    public ?int $teamId;
    /** `strTeam` */
    public ?string $team;
    /** `strHome`: true for the home side */
    public ?bool $isHome;
    /** `strSubstitute`: true for the bench */
    public ?bool $isSubstitute;
    /** `strPosition` */
    public ?string $position;
    /** `strPositionShort` (v2), e.g. `G`, `D` */
    public ?string $positionShort;
    /** `strFormation` (v2), e.g. `4-3-3` */
    public ?string $formation;
    /** `intSquadNumber` */
    public ?int $squadNumber;
    /** `strCountry` (v2) */
    public ?string $country;
    /** `strSeason` (v2) */
    public ?string $season;
    /** `strThumb` (v1) */
    public ?string $thumb;
    /** `strCutout` */
    public ?string $cutout;
    /** `strRender` (v1) */
    public ?string $render;
    /** `idAPIfootball` (v2) */
    public ?int $apiFootballId;

    /**
     * @internal Records are built by the client from API responses.
     * @param array<string, string|null> $raw
     */
    public function __construct(array $raw)
    {
        parent::__construct($raw);
        $r = new Rec($raw);
        $this->id = $r->id('idLineup');
        $this->eventId = $r->id('idEvent');
        $this->event = $r->s('strEvent');
        $this->playerId = $r->id('idPlayer');
        $this->player = $r->s('strPlayer');
        $this->teamId = $r->id('idTeam');
        $this->team = $r->s('strTeam');
        $this->isHome = $r->bool('strHome');
        $this->isSubstitute = $r->bool('strSubstitute');
        $this->position = $r->s('strPosition');
        $this->positionShort = $r->s('strPositionShort');
        $this->formation = $r->s('strFormation');
        $this->squadNumber = $r->int('intSquadNumber');
        $this->country = $r->s('strCountry');
        $this->season = $r->s('strSeason');
        $this->thumb = $r->s('strThumb');
        $this->cutout = $r->s('strCutout');
        $this->render = $r->s('strRender');
        $this->apiFootballId = $r->id('idAPIfootball');
    }

    public function __toString(): string
    {
        return "LineupEntry(eventId={$this->fmt($this->eventId)}, player={$this->fmt($this->player)}, team={$this->fmt($this->team)})";
    }
}
