<?php

// GENERATED by php/tools/gen_models.py from the Kotlin model LiveScore. Do not edit.

declare(strict_types=1);

namespace RohanG27\TheSportsDb\Model;

use RohanG27\TheSportsDb\Internal\Rec;

/**
 * A game in progress (`livescore.php`, `livescore/...`).
 */
final readonly class LiveScore extends ApiRecord
{
    /** `idLiveScore` */
    public ?int $id;
    /** `idEvent` */
    public ?int $eventId;
    /** `strSport` */
    public ?string $sport;
    /** `idLeague` */
    public ?int $leagueId;
    /** `strLeague` */
    public ?string $league;
    /** `intDivision` */
    public ?int $division;
    /** `idHomeTeam` */
    public ?int $homeTeamId;
    /** `strHomeTeam` */
    public ?string $homeTeam;
    /** `strHomeTeamBadge` */
    public ?string $homeTeamBadge;
    /** `idAwayTeam` */
    public ?int $awayTeamId;
    /** `strAwayTeam` */
    public ?string $awayTeam;
    /** `strAwayTeamBadge` */
    public ?string $awayTeamBadge;
    /** `intHomeScore` */
    public ?int $homeScore;
    /** `intAwayScore` */
    public ?int $awayScore;
    /** `strStatus`: the raw code; see [status] */
    public ?string $statusCode;
    /** `strProgress`: the minute (soccer) or `Final` */
    public ?string $progress;
    /** `strEventTime`: kick-off, `HH:mm` (HH:MM:SS) */
    public ?string $eventTime;
    /** `dateEvent` (a date, as midnight UTC) */
    public ?\DateTimeImmutable $date;
    /** `strTimestamp`: kick-off, UTC (UTC) */
    public ?\DateTimeImmutable $timestamp;
    /** `updated`: when this score was last refreshed (zone not stated) (zone not stated) */
    public ?\DateTimeImmutable $updated;

    /**
     * @internal Records are built by the client from API responses.
     * @param array<string, string|null> $raw
     */
    public function __construct(array $raw)
    {
        parent::__construct($raw);
        $r = new Rec($raw);
        $this->id = $r->id('idLiveScore');
        $this->eventId = $r->id('idEvent');
        $this->sport = $r->s('strSport');
        $this->leagueId = $r->id('idLeague');
        $this->league = $r->s('strLeague');
        $this->division = $r->int('intDivision');
        $this->homeTeamId = $r->id('idHomeTeam');
        $this->homeTeam = $r->s('strHomeTeam');
        $this->homeTeamBadge = $r->s('strHomeTeamBadge');
        $this->awayTeamId = $r->id('idAwayTeam');
        $this->awayTeam = $r->s('strAwayTeam');
        $this->awayTeamBadge = $r->s('strAwayTeamBadge');
        $this->homeScore = $r->int('intHomeScore');
        $this->awayScore = $r->int('intAwayScore');
        $this->statusCode = $r->s('strStatus');
        $this->progress = $r->s('strProgress');
        $this->eventTime = $r->time('strEventTime');
        $this->date = $r->date('dateEvent');
        $this->timestamp = $r->instant('strTimestamp');
        $this->updated = $r->localDateTime('updated');
    }

    public function __toString(): string
    {
        return "LiveScore(eventId={$this->fmt($this->eventId)}, homeTeam={$this->fmt($this->homeTeam)}, homeScore={$this->fmt($this->homeScore)}, awayScore={$this->fmt($this->awayScore)}, awayTeam={$this->fmt($this->awayTeam)}, statusCode={$this->fmt($this->statusCode)})";
    }

    /** The status code read as a broad status. */
    public function status(): EventStatus
    {
        return EventStatus::of($this->statusCode);
    }
}
