<?php

// GENERATED by php/tools/gen_models.py from the Kotlin model Milestone. Do not edit.

declare(strict_types=1);

namespace SportsDb\Model;

use SportsDb\Internal\Rec;

/**
 * A career milestone or award (`lookupmilestones.php`, `lookup/player_milestones`).
 */
final readonly class Milestone extends ApiRecord
{
    /** `id` */
    public ?int $id;
    /** `idMilestone` */
    public ?int $milestoneId;
    /** `strMilestone` */
    public ?string $name;
    /** `dateMilestone` (a date, as midnight UTC) */
    public ?\DateTimeImmutable $date;
    /** `idPlayer` */
    public ?int $playerId;
    /** `strPlayer` */
    public ?string $player;
    /** `idTeam` */
    public ?int $teamId;
    /** `strTeam` */
    public ?string $team;
    /** `strSport` */
    public ?string $sport;
    /** `strMilestoneLogo` */
    public ?string $logo;

    /**
     * @internal Records are built by the client from API responses.
     * @param array<string, string|null> $raw
     */
    public function __construct(array $raw)
    {
        parent::__construct($raw);
        $r = new Rec($raw);
        $this->id = $r->id('id');
        $this->milestoneId = $r->id('idMilestone');
        $this->name = $r->s('strMilestone');
        $this->date = $r->date('dateMilestone');
        $this->playerId = $r->id('idPlayer');
        $this->player = $r->s('strPlayer');
        $this->teamId = $r->id('idTeam');
        $this->team = $r->s('strTeam');
        $this->sport = $r->s('strSport');
        $this->logo = $r->s('strMilestoneLogo');
    }

    public function __toString(): string
    {
        return "Milestone(player={$this->fmt($this->player)}, name={$this->fmt($this->name)}, date={$this->fmt($this->date)})";
    }
}
