<?php

// GENERATED by php/tools/gen_models.py from the Kotlin model PlayerStat. Do not edit.

declare(strict_types=1);

namespace RohanG27\TheSportsDb\Model;

use RohanG27\TheSportsDb\Internal\Rec;

/**
 * One statistic for a player in one season (`lookupplayerstats.php`, `lookup/player_stats`).
 */
final readonly class PlayerStat extends ApiRecord
{
    /** `id` */
    public ?int $id;
    /** `idPlayer` */
    public ?int $playerId;
    /** `strPlayer` */
    public ?string $player;
    /** `idTeam` */
    public ?int $teamId;
    /** `strTeam` */
    public ?string $team;
    /** `strTeamBadge` */
    public ?string $teamBadge;
    /** `idLeague` */
    public ?int $leagueId;
    /** `strLeague` */
    public ?string $league;
    /** `strLeagueBadge` */
    public ?string $leagueBadge;
    /** `strSeason` */
    public ?string $season;
    /** `strSport` */
    public ?string $sport;
    /** `strStatistic`, e.g. `Goals`, `Appearances`, `Mins Played` */
    public ?string $statistic;
    /** `strValue`, as text */
    public ?string $value;

    /**
     * @internal Records are built by the client from API responses.
     * @param array<string, string|null> $raw
     */
    public function __construct(array $raw)
    {
        parent::__construct($raw);
        $r = new Rec($raw);
        $this->id = $r->id('id');
        $this->playerId = $r->id('idPlayer');
        $this->player = $r->s('strPlayer');
        $this->teamId = $r->id('idTeam');
        $this->team = $r->s('strTeam');
        $this->teamBadge = $r->s('strTeamBadge');
        $this->leagueId = $r->id('idLeague');
        $this->league = $r->s('strLeague');
        $this->leagueBadge = $r->s('strLeagueBadge');
        $this->season = $r->s('strSeason');
        $this->sport = $r->s('strSport');
        $this->statistic = $r->s('strStatistic');
        $this->value = $r->s('strValue');
    }

    public function __toString(): string
    {
        return "PlayerStat(player={$this->fmt($this->player)}, season={$this->fmt($this->season)}, statistic={$this->fmt($this->statistic)}, value={$this->fmt($this->value)})";
    }

    /** `value` as a number, when it is one. */
    public function numericValue(): ?float
    {
        return $this->value !== null && is_numeric(trim($this->value)) ? (float) trim($this->value) : null;
    }
}
