<?php

// GENERATED by php/tools/gen_models.py from the Kotlin model Player. Do not edit.

declare(strict_types=1);

namespace SportsDb\Model;

use SportsDb\Internal\Rec;

/**
 * A player, manager or other person. Search and list endpoints fill only some fields;
 * look the player up by id for the rest.
 */
final readonly class Player extends ApiRecord
{
    /** `idPlayer` */
    public ?int $id;
    /** `strPlayer` */
    public ?string $name;
    /** `strPlayerAlternate` */
    public ?string $alternateName;
    /** `strLastName` */
    public ?string $lastName;
    /** `idTeam` */
    public ?int $teamId;
    /** `strTeam` */
    public ?string $team;
    /** `idTeam2` */
    public ?int $secondTeamId;
    /** `strTeam2`, often the national team */
    public ?string $secondTeam;
    /** `idTeamNational` */
    public ?int $nationalTeamId;
    /** `idPlayerManager`: this person's record as a manager */
    public ?int $managerId;
    /** `strSport` */
    public ?string $sport;
    /** `strNationality` */
    public ?string $nationality;
    /** `strPosition` */
    public ?string $position;
    /** `strNumber`: the shirt number, as text */
    public ?string $number;
    /** `strStatus`, e.g. `Active`, `Retired` */
    public ?string $status;
    /** `strGender` */
    public ?string $gender;
    /** `dateBorn` (a date, as midnight UTC) */
    public ?\DateTimeImmutable $born;
    /** `strBirthLocation` */
    public ?string $birthLocation;
    /** `dateDied` (a date, as midnight UTC) */
    public ?\DateTimeImmutable $died;
    /** `strDeathLocation` */
    public ?string $deathLocation;
    /** `dateSigned` (a date, as midnight UTC) */
    public ?\DateTimeImmutable $signed;
    /** `strSigning`: the fee as text, e.g. `£25.20m` */
    public ?string $signing;
    /** `strWage`, as text */
    public ?string $wage;
    /** `strAgent` */
    public ?string $agent;
    /** `strHeight`, as text: `1.82 m (6 ft 0 in)` or `186 cm` */
    public ?string $height;
    /** `strWeight`, as text */
    public ?string $weight;
    /** `strSide`: `Left`/`Right` (preferred foot or hand) */
    public ?string $side;
    /** `strKit`: boot or equipment model */
    public ?string $kit;
    /** `strOutfitter` */
    public ?string $outfitter;
    /** `strCollege` */
    public ?string $college;
    /** `strEthnicity` */
    public ?string $ethnicity;
    /** `strThumb` */
    public ?string $thumb;
    /** `strCutout`: transparent head-and-shoulders */
    public ?string $cutout;
    /** `strRender`: transparent full body */
    public ?string $render;
    /** `strCartoon` */
    public ?string $cartoon;
    /** `strBanner` */
    public ?string $banner;
    /** `strPoster` */
    public ?string $poster;
    /** @var list<string> `strFanart1`..`strFanart4` */
    public array $fanart;
    /** `strCreativeCommons`: whether the artwork is Creative Commons. TheSportsDB's terms say artwork that isn't (false or null) must not be used in published apps. */
    public ?bool $creativeCommons;
    /** `strCreativeCommonsAttribution`: the credit line to show */
    public ?string $creativeCommonsAttribution;
    /** @var array<string, string> `strDescriptionEN`, ... keyed by language code */
    public array $descriptions;
    public Socials $socials;
    /** `intLoved` */
    public ?int $loved;
    /** `strLocked` */
    public ?bool $isLocked;
    /** `relevance`: search score (v1 `searchplayers.php` only) */
    public ?float $relevance;
    public PlayerExternalIds $externalIds;

    /**
     * @internal Records are built by the client from API responses.
     * @param array<string, string|null> $raw
     */
    public function __construct(array $raw)
    {
        parent::__construct($raw);
        $r = new Rec($raw);
        $this->id = $r->id('idPlayer');
        $this->name = $r->s('strPlayer');
        $this->alternateName = $r->s('strPlayerAlternate');
        $this->lastName = $r->s('strLastName');
        $this->teamId = $r->id('idTeam');
        $this->team = $r->s('strTeam');
        $this->secondTeamId = $r->id('idTeam2');
        $this->secondTeam = $r->s('strTeam2');
        $this->nationalTeamId = $r->id('idTeamNational');
        $this->managerId = $r->id('idPlayerManager');
        $this->sport = $r->s('strSport');
        $this->nationality = $r->s('strNationality');
        $this->position = $r->s('strPosition');
        $this->number = $r->s('strNumber');
        $this->status = $r->s('strStatus');
        $this->gender = $r->s('strGender');
        $this->born = $r->date('dateBorn');
        $this->birthLocation = $r->s('strBirthLocation');
        $this->died = $r->date('dateDied');
        $this->deathLocation = $r->s('strDeathLocation');
        $this->signed = $r->date('dateSigned');
        $this->signing = $r->s('strSigning');
        $this->wage = $r->s('strWage');
        $this->agent = $r->s('strAgent');
        $this->height = $r->s('strHeight');
        $this->weight = $r->s('strWeight');
        $this->side = $r->s('strSide');
        $this->kit = $r->s('strKit');
        $this->outfitter = $r->s('strOutfitter');
        $this->college = $r->s('strCollege');
        $this->ethnicity = $r->s('strEthnicity');
        $this->thumb = $r->s('strThumb');
        $this->cutout = $r->s('strCutout');
        $this->render = $r->s('strRender');
        $this->cartoon = $r->s('strCartoon');
        $this->banner = $r->s('strBanner');
        $this->poster = $r->s('strPoster');
        $this->fanart = $r->numbered('strFanart', 4);
        $this->creativeCommons = $r->bool('strCreativeCommons');
        $this->creativeCommonsAttribution = $r->s('strCreativeCommonsAttribution');
        $this->descriptions = $r->descriptions();
        $this->socials = Socials::fromRec($r);
        $this->loved = $r->int('intLoved');
        $this->isLocked = $r->locked();
        $this->relevance = $r->float('relevance');
        $this->externalIds = new PlayerExternalIds($r->id('idAPIfootball'), $r->s('idESPN'), $r->s('idGoogle'), $r->s('idTransferMkt'), $r->s('idWikidata'), $r->s('intSoccerXMLTeamID'));
    }

    public function __toString(): string
    {
        return "Player(id={$this->fmt($this->id)}, name={$this->fmt($this->name)}, team={$this->fmt($this->team)})";
    }

    /** The English description. */
    public function description(): ?string
    {
        return $this->descriptions['EN'] ?? null;
    }
}
