<?php

// GENERATED by php/tools/gen_models.py from the Kotlin model Season. Do not edit.

declare(strict_types=1);

namespace SportsDb\Model;

use SportsDb\Internal\Rec;

/**
 * A season of a league (`search_all_seasons.php`, `list/seasons`).
 */
final readonly class Season extends ApiRecord
{
    /** `strSeason`, e.g. `2026-2027` */
    public string $name;
    /** `strBadge` (v2, or v1 with `badge=1`) */
    public ?string $badge;
    /** `strPoster` (v2, or v1 with `poster=1`) */
    public ?string $poster;
    /** `strDescriptionEN` (v2, or v1 with `description=1`) */
    public ?string $description;

    /**
     * @internal Records are built by the client from API responses.
     * @param array<string, string|null> $raw
     */
    public function __construct(array $raw)
    {
        parent::__construct($raw);
        $r = new Rec($raw);
        $this->name = $r->s('strSeason') ?? '';
        $this->badge = $r->s('strBadge');
        $this->poster = $r->s('strPoster');
        $this->description = $r->s('strDescriptionEN');
    }

    public function __toString(): string
    {
        return "Season(name={$this->fmt($this->name)})";
    }
}
