<?php

// GENERATED by php/tools/gen_models.py from the Kotlin model SeasonPoster. Do not edit.

declare(strict_types=1);

namespace RohanG27\TheSportsDb\Model;

use RohanG27\TheSportsDb\Internal\Rec;

/**
 * One season poster or badge uploaded for a league (v2 `list/seasonposters`). A season can have
 * several; each is a separate piece of artwork with its own id.
 */
final readonly class SeasonPoster extends ApiRecord
{
    /** `idArt`: this artwork's id */
    public ?int $id;
    /** `idLeague` */
    public ?int $leagueId;
    /** `strSeason`, e.g. `2025-2026` */
    public ?string $season;
    /** `strPoster` */
    public ?string $poster;
    /** `strBadge` */
    public ?string $badge;
    /** `strDescriptionEN` */
    public ?string $description;
    /** `strUsername`: who uploaded it */
    public ?string $uploadedBy;

    /**
     * @internal Records are built by the client from API responses.
     * @param array<string, string|null> $raw
     */
    public function __construct(array $raw)
    {
        parent::__construct($raw);
        $r = new Rec($raw);
        $this->id = $r->id('idArt');
        $this->leagueId = $r->id('idLeague');
        $this->season = $r->s('strSeason');
        $this->poster = $r->s('strPoster');
        $this->badge = $r->s('strBadge');
        $this->description = $r->s('strDescriptionEN');
        $this->uploadedBy = $r->s('strUsername');
    }

    public function __toString(): string
    {
        return "SeasonPoster(id={$this->fmt($this->id)}, season={$this->fmt($this->season)})";
    }
}
