<?php

// GENERATED by php/tools/gen_models.py from the Kotlin model Sport. Do not edit.

declare(strict_types=1);

namespace RohanG27\TheSportsDb\Model;

use RohanG27\TheSportsDb\Internal\Rec;

/**
 * A sport (`all_sports.php`, `all/sports`).
 */
final readonly class Sport extends ApiRecord
{
    /** `idSport` */
    public ?int $id;
    /** `strSport`, e.g. `Ice Hockey`. Use this name for sport filters. */
    public ?string $name;
    /** `strFormat`: `TeamvsTeam` or `EventSport`. */
    public ?string $format;
    /** `strSportDescription` */
    public ?string $description;
    /** `strSportThumb` */
    public ?string $thumb;
    /** `strSportThumbBW` */
    public ?string $thumbBlackAndWhite;
    /** `strSportIconGreen` */
    public ?string $icon;

    /**
     * @internal Records are built by the client from API responses.
     * @param array<string, string|null> $raw
     */
    public function __construct(array $raw)
    {
        parent::__construct($raw);
        $r = new Rec($raw);
        $this->id = $r->id('idSport');
        $this->name = $r->s('strSport');
        $this->format = $r->s('strFormat');
        $this->description = $r->s('strSportDescription');
        $this->thumb = $r->s('strSportThumb');
        $this->thumbBlackAndWhite = $r->s('strSportThumbBW');
        $this->icon = $r->s('strSportIconGreen');
    }

    public function __toString(): string
    {
        return "Sport(id={$this->fmt($this->id)}, name={$this->fmt($this->name)})";
    }
}
