<?php

// GENERATED by php/tools/gen_models.py from the Kotlin model Standing. Do not edit.

declare(strict_types=1);

namespace SportsDb\Model;

use SportsDb\Internal\Rec;

/**
 * One row of a league table (`lookuptable.php`). v1 only; there is no v2 equivalent.
 */
final readonly class Standing extends ApiRecord
{
    /** `idStanding` */
    public ?int $id;
    /** `intRank` */
    public ?int $rank;
    /** `idTeam` */
    public ?int $teamId;
    /** `strTeam` */
    public ?string $team;
    /** `strBadge` */
    public ?string $badge;
    /** `idLeague` */
    public ?int $leagueId;
    /** `strLeague` */
    public ?string $league;
    /** `strSeason` */
    public ?string $season;
    /** `strGroup` */
    public ?string $group;
    /** `strForm`: recent results, newest last, e.g. `WWDLW` */
    public ?string $form;
    /** `strDescription`: what this position leads to, e.g. `Promotion - Champions League` */
    public ?string $description;
    /** `intPlayed` */
    public ?int $played;
    /** `intWin` */
    public ?int $won;
    /** `intDraw` */
    public ?int $drawn;
    /** `intLoss` */
    public ?int $lost;
    /** `intGoalsFor` */
    public ?int $goalsFor;
    /** `intGoalsAgainst` */
    public ?int $goalsAgainst;
    /** `intGoalDifference` */
    public ?int $goalDifference;
    /** `intPoints` */
    public ?int $points;
    /** `dateUpdated` (zone not stated) (zone not stated) */
    public ?\DateTimeImmutable $updated;

    /**
     * @internal Records are built by the client from API responses.
     * @param array<string, string|null> $raw
     */
    public function __construct(array $raw)
    {
        parent::__construct($raw);
        $r = new Rec($raw);
        $this->id = $r->id('idStanding');
        $this->rank = $r->int('intRank');
        $this->teamId = $r->id('idTeam');
        $this->team = $r->s('strTeam');
        $this->badge = $r->s('strBadge');
        $this->leagueId = $r->id('idLeague');
        $this->league = $r->s('strLeague');
        $this->season = $r->s('strSeason');
        $this->group = $r->s('strGroup');
        $this->form = $r->s('strForm');
        $this->description = $r->s('strDescription');
        $this->played = $r->int('intPlayed');
        $this->won = $r->int('intWin');
        $this->drawn = $r->int('intDraw');
        $this->lost = $r->int('intLoss');
        $this->goalsFor = $r->int('intGoalsFor');
        $this->goalsAgainst = $r->int('intGoalsAgainst');
        $this->goalDifference = $r->int('intGoalDifference');
        $this->points = $r->int('intPoints');
        $this->updated = $r->localDateTime('dateUpdated');
    }

    public function __toString(): string
    {
        return "Standing(rank={$this->fmt($this->rank)}, team={$this->fmt($this->team)}, points={$this->fmt($this->points)})";
    }
}
