<?php

// GENERATED by php/tools/gen_models.py from the Kotlin model Team. Do not edit.

declare(strict_types=1);

namespace RohanG27\TheSportsDb\Model;

use RohanG27\TheSportsDb\Internal\Rec;

/**
 * A team. Search and list endpoints fill only some fields (v2 `list/teams` has no
 * alternate names, for example); a lookup by id fills them all.
 */
final readonly class Team extends ApiRecord
{
    /** `idTeam` */
    public ?int $id;
    /** `strTeam` */
    public ?string $name;
    /** `strTeamShort`, e.g. `ARS` */
    public ?string $shortName;
    /** @var list<string> `strTeamAlternate`, split on commas */
    public array $alternateNames;
    /** @var list<string> `strKeywords`, split on commas (nicknames) */
    public array $keywords;
    /** `strSport` */
    public ?string $sport;
    /** `strGender` */
    public ?string $gender;
    /** `strCountry` */
    public ?string $country;
    /** `strLocation` */
    public ?string $location;
    /** `intFormedYear` */
    public ?int $formedYear;
    /** `idLeague`/`strLeague`: the main league */
    public ?int $leagueId;
    /** `strLeague` */
    public ?string $league;
    /** @var list<LeagueRef> Every league and cup the team is entered in: `idLeague`..`idLeague7` with their names */
    public array $leagues;
    /** `strDivision` */
    public ?string $division;
    /** `idVenue` */
    public ?int $venueId;
    /** `strStadium` */
    public ?string $stadium;
    /** @var list<string> `strColour1`..`strColour3`, hex like `#EF0107` */
    public array $colours;
    /** `strBadge` */
    public ?string $badge;
    /** `strLogo` */
    public ?string $logo;
    /** `strBanner` */
    public ?string $banner;
    /** `strEquipment`: the current kit image */
    public ?string $equipment;
    /** @var list<string> `strFanart1`..`strFanart4` */
    public array $fanart;
    /** @var array<string, string> `strDescriptionEN`, `strDescriptionDE`, ... keyed by language code */
    public array $descriptions;
    public Socials $socials;
    /** `intLoved` */
    public ?int $loved;
    /** `strLocked` */
    public ?bool $isLocked;
    /** `idAPIfootball` */
    public ?int $apiFootballId;
    /** `idESPN` */
    public ?string $espnId;

    /**
     * @internal Records are built by the client from API responses.
     * @param array<string, string|null> $raw
     */
    public function __construct(array $raw)
    {
        parent::__construct($raw);
        $r = new Rec($raw);
        $this->id = $r->id('idTeam');
        $this->name = $r->s('strTeam');
        $this->shortName = $r->s('strTeamShort');
        $this->alternateNames = $r->csv('strTeamAlternate');
        $this->keywords = $r->csv('strKeywords');
        $this->sport = $r->s('strSport');
        $this->gender = $r->s('strGender');
        $this->country = $r->s('strCountry');
        $this->location = $r->s('strLocation');
        $this->formedYear = $r->year('intFormedYear');
        $this->leagueId = $r->id('idLeague');
        $this->league = $r->s('strLeague');
        $this->leagues = self::leagues($r);
        $this->division = $r->s('strDivision');
        $this->venueId = $r->id('idVenue');
        $this->stadium = $r->s('strStadium');
        $this->colours = $r->numbered('strColour', 3);
        $this->badge = $r->s('strBadge');
        $this->logo = $r->s('strLogo');
        $this->banner = $r->s('strBanner');
        $this->equipment = $r->s('strEquipment');
        $this->fanart = $r->numbered('strFanart', 4);
        $this->descriptions = $r->descriptions();
        $this->socials = Socials::fromRec($r);
        $this->loved = $r->int('intLoved');
        $this->isLocked = $r->locked();
        $this->apiFootballId = $r->id('idAPIfootball');
        $this->espnId = $r->s('idESPN');
    }

    public function __toString(): string
    {
        return "Team(id={$this->fmt($this->id)}, name={$this->fmt($this->name)})";
    }

    /** The English description. */
    public function description(): ?string
    {
        return $this->descriptions['EN'] ?? null;
    }

    /** @return list<LeagueRef> */
    private static function leagues(Rec $r): array
    {
        $out = [];
        for ($n = 1; $n <= 7; $n++) {
            $suffix = $n === 1 ? '' : (string) $n;
            if (($id = $r->id("idLeague$suffix")) !== null) {
                $out[] = new LeagueRef($id, $r->s("strLeague$suffix"));
            }
        }
        return $out;
    }
}
