<?php

// GENERATED by php/tools/gen_models.py from the Kotlin model TimelineEntry. Do not edit.

declare(strict_types=1);

namespace SportsDb\Model;

use SportsDb\Internal\Rec;

/**
 * A goal, card or substitution during an event (`lookuptimeline.php`, `lookup/event_timeline`).
 */
final readonly class TimelineEntry extends ApiRecord
{
    /** `idTimeline` */
    public ?int $id;
    /** `idEvent` */
    public ?int $eventId;
    /** `strEvent` */
    public ?string $event;
    /** `dateEvent` (a date, as midnight UTC) */
    public ?\DateTimeImmutable $date;
    /** `strSeason` */
    public ?string $season;
    /** `intTime`: the minute */
    public ?int $minute;
    /** `strPeriod` */
    public ?string $period;
    /** `strTimeline`: the kind of entry, e.g. `Goal`, `Card`, `subst` */
    public ?string $type;
    /** `strTimelineDetail`, e.g. `Yellow Card`, `Normal Goal`, or the player coming on */
    public ?string $detail;
    /** `strComment` */
    public ?string $comment;
    /** `idPlayer` */
    public ?int $playerId;
    /** `strPlayer` */
    public ?string $player;
    /** `strCutout` */
    public ?string $cutout;
    /** `idAssist` */
    public ?int $assistId;
    /** `strAssist` */
    public ?string $assist;
    /** `idTeam` */
    public ?int $teamId;
    /** `strTeam` */
    public ?string $team;
    /** `strHome` */
    public ?bool $isHome;
    /** `idAPIfootball` */
    public ?int $apiFootballId;

    /**
     * @internal Records are built by the client from API responses.
     * @param array<string, string|null> $raw
     */
    public function __construct(array $raw)
    {
        parent::__construct($raw);
        $r = new Rec($raw);
        $this->id = $r->id('idTimeline');
        $this->eventId = $r->id('idEvent');
        $this->event = $r->s('strEvent');
        $this->date = $r->date('dateEvent');
        $this->season = $r->s('strSeason');
        $this->minute = $r->int('intTime');
        $this->period = $r->s('strPeriod');
        $this->type = $r->s('strTimeline');
        $this->detail = $r->s('strTimelineDetail');
        $this->comment = $r->s('strComment');
        $this->playerId = $r->id('idPlayer');
        $this->player = $r->s('strPlayer');
        $this->cutout = $r->s('strCutout');
        $this->assistId = $r->id('idAssist');
        $this->assist = $r->s('strAssist');
        $this->teamId = $r->id('idTeam');
        $this->team = $r->s('strTeam');
        $this->isHome = $r->bool('strHome');
        $this->apiFootballId = $r->id('idAPIfootball');
    }

    public function __toString(): string
    {
        return "TimelineEntry(eventId={$this->fmt($this->eventId)}, minute={$this->fmt($this->minute)}, type={$this->fmt($this->type)}, player={$this->fmt($this->player)})";
    }
}
