<?php

// GENERATED by php/tools/gen_models.py from the Kotlin model TvListing. Do not edit.

declare(strict_types=1);

namespace SportsDb\Model;

use SportsDb\Internal\Rec;

/**
 * One broadcast of an event on one channel (v1 `lookuptv.php`/`eventstv.php`, v2 `lookup/event_tv`/`filter/tv`).
 */
final readonly class TvListing extends ApiRecord
{
    /** `id` */
    public ?int $id;
    /** `idEvent` */
    public ?int $eventId;
    /** `strEvent` */
    public ?string $event;
    /** `strSport` */
    public ?string $sport;
    /** `strSeason` */
    public ?string $season;
    /** `idChannel` */
    public ?int $channelId;
    /** `strChannel`, e.g. `TSN 1` */
    public ?string $channel;
    /** `strLogo`: the channel logo */
    public ?string $channelLogo;
    /** `strCountry`: the channel's country */
    public ?string $country;
    /** `strEventCountry`: where the event takes place */
    public ?string $eventCountry;
    /** `strTimeStamp` (capital S, space-separated in the API): broadcast start, UTC (UTC) */
    public ?\DateTimeImmutable $timestamp;
    /** `dateEvent` (a date, as midnight UTC) */
    public ?\DateTimeImmutable $date;
    /** `strTime` (HH:MM:SS) */
    public ?string $time;
    /** `intDivision` */
    public ?int $division;
    /** `strEventThumb` */
    public ?string $eventThumb;
    /** `strEventPoster` */
    public ?string $eventPoster;
    /** `strEventBanner` */
    public ?string $eventBanner;
    /** `strEventSquare` */
    public ?string $eventSquare;

    /**
     * @internal Records are built by the client from API responses.
     * @param array<string, string|null> $raw
     */
    public function __construct(array $raw)
    {
        parent::__construct($raw);
        $r = new Rec($raw);
        $this->id = $r->id('id');
        $this->eventId = $r->id('idEvent');
        $this->event = $r->s('strEvent');
        $this->sport = $r->s('strSport');
        $this->season = $r->s('strSeason');
        $this->channelId = $r->id('idChannel');
        $this->channel = $r->s('strChannel');
        $this->channelLogo = $r->s('strLogo');
        $this->country = $r->s('strCountry');
        $this->eventCountry = $r->s('strEventCountry');
        $this->timestamp = $r->instant('strTimeStamp') ?? $r->instant('strTimestamp');
        $this->date = $r->date('dateEvent');
        $this->time = $r->time('strTime');
        $this->division = $r->int('intDivision');
        $this->eventThumb = $r->s('strEventThumb');
        $this->eventPoster = $r->s('strEventPoster');
        $this->eventBanner = $r->s('strEventBanner');
        $this->eventSquare = $r->s('strEventSquare');
    }

    public function __toString(): string
    {
        return "TvListing(eventId={$this->fmt($this->eventId)}, channel={$this->fmt($this->channel)}, timestamp={$this->fmt($this->timestamp)})";
    }
}
