<?php

// GENERATED by php/tools/gen_models.py from the Kotlin model Venue. Do not edit.

declare(strict_types=1);

namespace RohanG27\TheSportsDb\Model;

use RohanG27\TheSportsDb\Internal\Rec;

/**
 * A stadium, arena or circuit.
 */
final readonly class Venue extends ApiRecord
{
    /** `idVenue` */
    public ?int $id;
    /** `strVenue` */
    public ?string $name;
    /** `strVenueAlternate` */
    public ?string $alternateName;
    /** `strVenueSponsor` */
    public ?string $sponsorName;
    /** `strSport` */
    public ?string $sport;
    /** `strLocation` */
    public ?string $location;
    /** `strCountry` */
    public ?string $country;
    /** `strTimezone`, as text, e.g. `UTC +00:00 Greenwich Mean Time (GMT)` */
    public ?string $timezone;
    /** `intCapacity` */
    public ?int $capacity;
    /** `intFormedYear` */
    public ?int $formedYear;
    /** `strArchitect` */
    public ?string $architect;
    /** `strCost`, as text */
    public ?string $cost;
    /** `strMap`: either `lat, lon` or an image URL */
    public ?string $map;
    /** `strThumb` */
    public ?string $thumb;
    /** `strLogo` */
    public ?string $logo;
    /** @var list<string> `strFanart1`..`strFanart4` */
    public array $fanart;
    /** `strCreativeCommons`: see [Player.creativeCommons] */
    public ?bool $creativeCommons;
    /** @var array<string, string> `strDescriptionEN`, ... */
    public array $descriptions;
    public Socials $socials;
    /** `intLoved` */
    public ?int $loved;
    /** `strLocked` */
    public ?bool $isLocked;
    /** `idDupe`: set when this record duplicates another venue */
    public ?int $duplicateOf;

    /**
     * @internal Records are built by the client from API responses.
     * @param array<string, string|null> $raw
     */
    public function __construct(array $raw)
    {
        parent::__construct($raw);
        $r = new Rec($raw);
        $this->id = $r->id('idVenue');
        $this->name = $r->s('strVenue');
        $this->alternateName = $r->s('strVenueAlternate');
        $this->sponsorName = $r->s('strVenueSponsor');
        $this->sport = $r->s('strSport');
        $this->location = $r->s('strLocation');
        $this->country = $r->s('strCountry');
        $this->timezone = $r->s('strTimezone');
        $this->capacity = $r->int('intCapacity');
        $this->formedYear = $r->year('intFormedYear');
        $this->architect = $r->s('strArchitect');
        $this->cost = $r->s('strCost');
        $this->map = $r->s('strMap');
        $this->thumb = $r->s('strThumb');
        $this->logo = $r->s('strLogo');
        $this->fanart = $r->numbered('strFanart', 4);
        $this->creativeCommons = $r->bool('strCreativeCommons');
        $this->descriptions = $r->descriptions();
        $this->socials = Socials::fromRec($r);
        $this->loved = $r->int('intLoved');
        $this->isLocked = $r->locked();
        $this->duplicateOf = $r->id('idDupe');
    }

    public function __toString(): string
    {
        return "Venue(id={$this->fmt($this->id)}, name={$this->fmt($this->name)})";
    }

    /** The English description. */
    public function description(): ?string
    {
        return $this->descriptions['EN'] ?? null;
    }

    /** @return array{float, float}|null `map` as [latitude, longitude], when it holds coordinates */
    public function coordinates(): ?array
    {
        $parts = array_map('trim', explode(',', $this->map ?? ''));
        return \count($parts) === 2 && is_numeric($parts[0]) && is_numeric($parts[1]) ? [(float) $parts[0], (float) $parts[1]] : null;
    }
}
